### ISSUE TITLE
On mac

### ISSUE THREAD

**Issue by vickris** [ifedapoolarewaju/igdm#1]
<img width="1197" alt="screen shot 2017-04-10 at 09 34 38" src="https://cloud.githubusercontent.com/assets/8840187/24848902/c5e118fe-1dd1-11e7-8bd8-1eecbfef5832.png">

after opening the app

**Comment by ifedapoolarewaju** [comment]
@vickris Thank you for reporting. What OS was it run on?

**Comment by vickris** [comment]
El capitan

**Comment by ifedapoolarewaju** [comment]
I have fixed the issue and released a version `1.0.2` you can download [here](https://github.com/ifedapoolarewaju/igdm/releases/download/1.0.2/IGdm.1.0.2.dmg), or download from the [website](https://ifedapoolarewaju.github.io/igdm/).

Please let me know if that works so I can close this issue :)

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/ifedapoolarewaju/igdm/commit/df31d74953d2bebd12bf884268ff2dcc03753817)
