### ISSUE TITLE
Impossible to send Links and Photos as DM

### ISSUE THREAD

**Issue by ikarusWillFly** [ifedapoolarewaju/igdm#100]
Hi, if i send a link in a Direct Message through instagram it allows the receiver to open the URL by clicking on it. If I use your (otherwise great) app, the link is pasted as plain text and i cant click on it.

sending Photo and videos as DM seems to be broken as well, i select the file but it is not sent. 

These are two very important functions for me.

Thanks

**Comment by vishwajeet97** [comment]
The same is happening to me as well, the photos are selected but not actually sent.

Thanks

**Comment by miz-takahashi** [comment]
> If I use your (otherwise great) app, the link is pasted as plain text and i cant click on it.

The same is happening to me as well.

**Comment by vishwajeet97** [comment]
An update: PNG format are not supported but the JPG format is working.
