### ISSUE TITLE
[Question] Login from ZTE U885 · Instagram app? 

### ISSUE THREAD

**Issue by arky** [ifedapoolarewaju/igdm#1008]
Wonder why Instagram "suspicious login attempt" email says I have logged in from "ZTE U885 · Instagram app" when I use IG:dm? 

Is this a security issue that I should be concerned about?

**Comment by codedaddy98** [comment]
That seems rather odd @arky but if it coincides exactly with when you're logging into IG:dm I think you should not be worried.

**Comment by ifedapoolarewaju** [comment]
this is not an issue. when IGdm communicates with Instagram, it presents itself as a mobile phone so that Instagram thinks that it's coming from the mobile app, but it is as a matter of fact coming from your computer.
