### ISSUE TITLE
IGDM stop working!!!!! Unable to see any chat message since 3-4 days. 

### ISSUE THREAD

**Issue by janak6625** [ifedapoolarewaju/igdm#1012]
since 2 days I am unable to see any chat message on IGDM , it stopped working.

**Comment by janak6625** [comment]
it's not working for me since 3-4 days, and I report an issue but no one reply to me.
I am using windows 10 Enterprise, i7 16GB ram

https://snag.gy/JOR41E.jpg

**Comment by ifedapoolarewaju** [comment]
could you try logging out and logging again?

**Comment by janak6625** [comment]
when i try to login again it shows me an error "Not possible to parse API response" and unable to login

**Comment by janak6625** [comment]
I am able to login with same credentials on the official Instagram mobile app but unable to login into IGDM

**Comment by janak6625** [comment]
when it will be fixed?  ? ? !! ? !! ??

**Comment by janak6625** [comment]
@ifedapoolarewaju  any update, are you working on this issue??? any clue?

**Comment by ifedapoolarewaju** [comment]
> Not possible to parse API response

This is an erratic issue that is often hard to reproduce. I haven't been able to find a fix for it yet.
The issue already exists [here](https://github.com/ifedapoolarewaju/igdm/issues/567), so I'll close this one as a duplicate.
