### ISSUE TITLE
using IG:Dm Pro crashes

### ISSUE THREAD

**Issue by cwevenson** [ifedapoolarewaju/igdm#1016]
I just bought IG:DM Pro and installed it but the application does not remain open when attempting to run it.  I do have a prior install of IG:DM which does work.

**Comment by ifedapoolarewaju** [comment]
could you try installing the version 1.3.3 instead? https://github.com/ifedapoolarewaju/igdm-pro-release/releases/tag/v1.3.3

**Comment by ifedapoolarewaju** [comment]
closing this as it should be reported here instead https://github.com/ifedapoolarewaju/igdm-pro-release/issues
