### ISSUE TITLE
IGdm new icon

### ISSUE THREAD

**Issue by bankks** [ifedapoolarewaju/igdm#103]
Hey guys, I'm opening an issue to discuss the idea of an new app icon:

If we want to offer the experience that user already has on mobile, we should follow the same branding and also interface colors, and icons everything. 

So that's one thing that would you guys have in mind because I'm working on the new UI and Icon based on these principles ok?

Lets go to icon then.

Instagram has it's app icon, and also an icon/button that means the direct message area.
Also our actual icon is too dark, so the idea here was to combine both things:

Instagram app icon + Direct message icon 

![image](https://user-images.githubusercontent.com/5085738/37191164-545814b2-2334-11e8-9ba8-9f0d925f1663.png)

**And the result would be this:**

![image](https://user-images.githubusercontent.com/5085738/37191190-84d28d48-2334-11e8-8ea6-5dd315bb35a1.png)

**on the launchpad:**

![image](https://user-images.githubusercontent.com/5085738/37191308-1d14f88e-2335-11e8-9d64-8cbb00083bee.png)

So, what you guys think?
Let me know your toughts

**Comment by ifedapoolarewaju** [comment]
yeah I like this icon, however, I fear that it doesn't immediately look like instagram, so one might be in the doubt whether or not it works with instagram

**Comment by bankks** [comment]
But the thing is, IGdm is not a Instagram client, I mean, the user can't see the photo feed and the stories. It's an messaging app, that's why I used the direct icon.

And also, if the used downloaded IGdm, they already have the context and the idea of the app, what is it's function: A desktop client for Instagram Direct Messaging.

Also the idea is, once we have the design guidelines, we'll align all the communication, like website and everything else with consistency, not just visual but all the experience.

So here's my point: if we let the "camera" icon like Instagram, it will look like an client to see photos, and not specificly to messaging.

But let's discuss to decide this :)

**Comment by bankks** [comment]
@ifedapoolarewaju  And what about the icon? is it ok?
Can I continue with this ?
Any other question or suggestion?

**Comment by ifedapoolarewaju** [comment]
@bankks yes, please 😉  (I thought I had responded here too already)
