### ISSUE TITLE
[Feature request] Use system proxy settings

### ISSUE THREAD

**Issue by fengshuo2004** [ifedapoolarewaju/igdm#1039]
IGDM doesn't seem to be using Windows system HTTP proxy settings.
I am using ShadowsocksR in China, in which you know, blocks Instagram.
After I connect the proxy, I am able to watch Youtube and visit other blocked website with my browser (Chrome) but I can't login to IGDM.
I am only able to do so when I switched to a TAP based VPN software, in my case, SSTAP.
(TAP based VPN uses a virtual network adapter to route all TCP and UDP traffic)

**Comment by fengshuo2004** [comment]
**Update:**
1. As a frontend developer I know that Electron based apps are able to use Windows system proxy setting.
2. I also know that Instagram has an API with HTTP protocol, not any other protocols.
3. IGDM is based on Electron

And then what? You guys are making a _paid_ version with configurable proxy setting?
You said it here: https://pro.igdm.me/
Really? Is that _really_ necesary? If you mind just to add a little proxy setting, why are you making an open source version and putting it on Github?
And _why_ are you putting ads in this open source version?
You do realise I can just fork your project, remove those ads then rebuild, right?
In fact I have already done that, guess you don't really mind me distributing my version since it is open source anyway?
Seriouly what's the point of that?

**Comment by ifedapoolarewaju** [comment]
Hi @fengshuo2004 , if there's a feature missing on IGdm that you find easy to implement, please feel free to submit a PR. If you'd rather create and maintain your own fork, that's fine too.

PS: there are no Ads added to any of the IGdm versions. The issue reported about Ads is an issue a user was facing and (s)he misinterpreted it to be Ads. If you read through the issue comments, you'd see my suggestions regarding what the issue could be.
