### ISSUE TITLE
IGdm new design

### ISSUE THREAD

**Issue by bankks** [ifedapoolarewaju/igdm#104]
Hello everyone,

As said at the Issue #103 about the new icon, If we want to offer the experience that user already has on mobile, we should follow the same branding and also interface colors, and icons everything.

So that's one thing that would you guys have in mind because I'm working on the new UI and Icon based on these principles ok?

This is how IG list the conversations on mobile:

![image](https://user-images.githubusercontent.com/5085738/37191389-93bb9bf0-2335-11e8-9711-5e4779e4c3b7.png)

And this is it's messaging screen:

![image](https://user-images.githubusercontent.com/5085738/37191454-1d875fa4-2336-11e8-996d-82dc9c570064.png)

So, combining both screens, and following the messaging apps patterns I designed this:

![image](https://user-images.githubusercontent.com/5085738/37191415-bcc90aaa-2335-11e8-851e-2d9122b0d88e.png)

I know, it's look kind boring, but I just followed the same design for now.
Of course, we can add a better look and feel, and some little micro-interactions and transition/animations.

But I think that it's clear, objective and also follow the Instagram Direct Message design guidelines.
So the user keep the experience about how their are already used to.

What do you guys think?
🙃

**Comment by ifedapoolarewaju** [comment]
@bankks honestly, I'm not sure we need another complete redesign after this https://github.com/ifedapoolarewaju/igdm/pull/87 I would think maybe we could improve on it from where that PR stopped? Are there any particular reasons why you think we should still go for a complete redesign?

**Comment by bankks** [comment]
I don't think it's a complete redesign, because the structure we already have today, even the same elements, it's just to make look like Instagram.

But I got your point.
I just followed an thinking line about what Instagram Direct Message already is .

I'm not saying that what we have today is not good, my idea was just to have consistence on the experience as a product and service.

I can try something between both things, not so far from what we have and more like Instagram?
Give me your toughts :)

**Comment by bankks** [comment]
There's no one best than another here, we are building this together, I can contribute more with design, but the idea is to we all bbe part of this right? So if you think that something can be better, say it! No problem at all my friend 🙃

**Comment by bankks** [comment]
So what would we do now @ifedapoolarewaju ?
How can we proceed?

**Comment by ifedapoolarewaju** [comment]
@bankks Oh I already shared my thoughts here https://github.com/ifedapoolarewaju/igdm/issues/104#issuecomment-372014975 which basically goes with your suggestion
