### ISSUE TITLE
url posted while sending standard message

### ISSUE THREAD

**Issue by cristogi** [ifedapoolarewaju/igdm#1046]
at random, when typing text message over the ID:dm desktop app on Mac OS and sending it, the app will attach a URL.

on the phone, that message shows as a media message to a weird article of shooting (see attachment) but the link to the article does not work.

I never read/open such an article and it's not possible that it would come from my clipboard.

![igdm-bug](https://user-images.githubusercontent.com/2158505/63270908-51d1ce80-c299-11e9-9484-ba57f5b48f92.png)

**Comment by aokomorowski** [comment]
Hi @cristogi, could you attach that URL?

**Comment by ifedapoolarewaju** [comment]
This issue is now fixed in the latest release

**Comment by ifedapoolarewaju** [comment]
@aokomorowski thank you for making the effort to resolve this ❤️
