### ISSUE TITLE
i cant login in my count bout the code verification not arrives

### ISSUE THREAD

**Issue by dmzz399** [ifedapoolarewaju/igdm#1047]

**Comment by dmzz399** [comment]
I can't get the verification code to my email I can't enter please help me.

**Comment by dmzz399** [comment]
None of that helped me with my problem. I just need the verification code to arrive to enter my igdm account please.

**Comment by dmzz399** [comment]
?¿

**Comment by ifedapoolarewaju** [comment]
this is an issue from instagram. It sometimes takes a while before they send an email containing the code. You can either wait a while, or try to login again. And also double-check your mailbox and your sms box
