### ISSUE TITLE
Can't remember login

### ISSUE THREAD

**Issue by XexuWilder** [ifedapoolarewaju/igdm#105]
The app can't remember the login data.

You have to write your credentials everytime the app opens

**Comment by ifedapoolarewaju** [comment]
@XexuWilder are you running it on a linux machine? If so please download this version https://github.com/ifedapoolarewaju/igdm/releases/download/v2.3.1/IGdm-2.3.1-x86_64.AppImage

**Comment by ifedapoolarewaju** [comment]
closing this because I can't reproduce, and I'm not getting a response
