### ISSUE TITLE
"Please enter the verification code sent to your e-mail address" the code never arrives...

### ISSUE THREAD

**Issue by awguo** [ifedapoolarewaju/igdm#1050]
Is there any solution for this?
Thanks

**Comment by awguo** [comment]
> * #1047 - i cant login in my count bout the code verification not arrives

This person is also looking for help....

You're not getting our points.

**Comment by ifedapoolarewaju** [comment]
this is an issue from instagram. It sometimes takes a while before they send an email containing the code. You can either wait a while, or try to login again. And also double-check your mailbox and your sms box

**Comment by awguo** [comment]
@ifedapoolarewaju I do receive an email on instant but I never get the code.

The title of the email is _New login to Instagram from Chrome on Mac OS X_

**Comment by awguo** [comment]
UPDATE, I got the SMS.

I guess you guys can update the text in the warning box. @ifedapoolarewaju 

Thanks!
