### ISSUE TITLE
Screen Resolution change

### ISSUE THREAD

**Issue by sibaar** [ifedapoolarewaju/igdm#109]
Y axis is fixed on ubuntu 17.10
windows does not fit on screen. 
consider option to modify screen resolution on user end
it's just far too big

**Comment by ifedapoolarewaju** [comment]
@sibaar this issue is fixed. Just yet to be released

**Comment by sibaar** [comment]
Should clarify that I'm having problems on Y axis. Height, not width.

**Comment by ifedapoolarewaju** [comment]
@sibaar this issue is now fixed here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.0
