### ISSUE TITLE
No support for replies to IG stories

### ISSUE THREAD

**Issue by solomon-fibonacci** [ifedapoolarewaju/igdm#11]
Reply to stories are shown as `<unsupported message format>`

**Comment by Mrkezii** [comment]
shown as what? @solomon-fibonacci

**Comment by solomon-fibonacci** [comment]
@Mrkezii I've edited the comment. The markdown parsing must have messed with it. My bad that I didn't notice tho. Thanks for the heads up!

**Comment by antoniomorais360** [comment]
<unsupported message format>
 05, Sep. 18:40 

Same error here.
![igdm-error](https://user-images.githubusercontent.com/2750015/31507429-06a92078-af51-11e7-8e50-eace2293023f.png)

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/ifedapoolarewaju/igdm/commit/8709be367f955d5ec8b4a0c087d204593bd2fc73) and [here](https://github.com/ifedapoolarewaju/igdm/commit/0d3dcaf91a7c87e962748e4a8d7c2f8ec97ce38b)

**Comment by lorealallen** [comment]
the problem is fixed thanks so much

**Comment by lorealallen** [comment]
it fixed
