### ISSUE TITLE
Bitcoin address is wrong

### ISSUE THREAD

**Issue by AddaxSoft** [ifedapoolarewaju/igdm#110]
n3NM9EubVwdvNm9qiTgLC8DHsRtTHvoyaD6 is not a valid bitcoin address

**Comment by ifedapoolarewaju** [comment]
wow, thank you for reporting this. It would have remained unnoticed forever

**Comment by AddaxSoft** [comment]
haha. I was also surprised - no worries! Maybe you can throw some bitcoins at me later ;)
31x5qUwNYSwkyDxtYwfdpB3tKi6rY9y42A
