### ISSUE TITLE
Can I use sessionid instead of username / password?

### ISSUE THREAD

**Issue by AddaxSoft** [ifedapoolarewaju/igdm#111]
I don't feel comfortable sharing user/pass with the app.
Can I use the sessionid as an authenticator

**Comment by ifedapoolarewaju** [comment]
I'm afraid not, your sessionid is also tied to some other metadata, e.g your device id, etc. So I think it's going to be a little too tricky to achieve this without much stress.

Although I do like the idea, so I'll keep this on my radar.
