### ISSUE TITLE
Missing Users Who Are Not Following Me on IG

### ISSUE THREAD

**Issue by UptownPhotography** [ifedapoolarewaju/igdm#116]
IG:DM did an update this morning and ever since the update there is no longer a way to check who is NOT Following me on Instagram. This was feature was very useful and no longer there on the upper right of page to click on. How do I get it back please. (or restore the app to the previous version) I am running windows 8.1. Thanks.

Philip

**Comment by ifedapoolarewaju** [comment]
Hello, this feature is still in place (on the top left).
<img width="422" alt="screen shot 2018-03-25 at 1 57 23 pm" src="https://user-images.githubusercontent.com/8383781/37875270-8b26cbc0-3034-11e8-9ad2-b5747c013b52.png">


Do you mind sharing a screenshot of what it looks like on your end

**Comment by UptownPhotography** [comment]
Thank you. I did not see that icon over on the Left. That helps very much having that feature. I thought I'd have to find a new app to track Followers from my PC. Thanks again.
