### ISSUE TITLE
Group chat names and icons

### ISSUE THREAD

**Issue by mohamed-ahmed** [ifedapoolarewaju/igdm#121]
* The group chat doesn't show the group's name, it just shows a list of group members. 

* Also the group icon is just of one member of the group.  An option would be to make it a combination of the group members icons like this
![image](https://user-images.githubusercontent.com/1468166/37977965-e689b9d0-31b2-11e8-8665-134a539cb1a8.png)

or maybe a group icon like this

![image](https://user-images.githubusercontent.com/1468166/37978116-46efb0e0-31b3-11e8-8d51-8d7af47d6f1c.png)

**Comment by swxft** [comment]
I don't even see how to start a group chat. How do you send a dm to multiple people?

**Comment by mohamed-ahmed** [comment]
@swxft you need to already have a group chat going on the IG app. You can create one through the official mobile app if you donn't have one in your inbox yet.

**Comment by mohamed-ahmed** [comment]
@ifedapoolarewaju why was this closed? Do you not think its a useful feature?

**Comment by ifedapoolarewaju** [comment]
the group name feature has been added to the latest version

**Comment by mohamed-ahmed** [comment]
👏 👏 👏

**Comment by ifedapoolarewaju** [comment]
lol yes, thanks to a good samaritan who submitted a PR :)
