### ISSUE TITLE
Please .deb Package?

### ISSUE THREAD

**Issue by federicosnobohm** [ifedapoolarewaju/igdm#126]
anyone haves the .deb package?

**Comment by ifedapoolarewaju** [comment]
this is now available in the latest version https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.1

**Comment by federicosnobohm** [comment]
thank you very much

El vie, 20 de abr 2018 a las 9:46 , Ifedapo .A. Olarewaju <notifications@github.com> escribió:

this is now available in the latest version https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.1
