### ISSUE TITLE
Instagram Desktop Messenger 

### ISSUE THREAD

**Issue by Mwicigi** [ifedapoolarewaju/igdm#128]
I logged in to my IG desktop messenger and all of my messages were gone what could be wrong with it?

**Comment by ifedapoolarewaju** [comment]
@Mwicigi do you still see your messages when you log back to your mobile phone?

**Comment by Mwicigi** [comment]
I have never installed IG on my phone will have to try that first

**Comment by ifedapoolarewaju** [comment]
oh, so your previous messages which you had gathered from IG:dm itself had gone? Is that you mean?
Did your chat list also get cleared?

**Comment by Mwicigi** [comment]
Yes my chat list is gone the interface is empty

**Comment by ifedapoolarewaju** [comment]
then it could rather be an internet/connection issue. Perhaps the chat isn't cleared, but IG:dm is unable to fetch them due to connection issue or some other error.

Are you able to start a new chat?

**Comment by Mwicigi** [comment]
I cant start a new chat as well

**Comment by ifedapoolarewaju** [comment]
then it's a connection issue for sure. can you share a screenshot of what the interface looks like on your end?

**Comment by Mwicigi** [comment]
![Uploading Screenshot (4).png…]()

**Comment by Mwicigi** [comment]
![screenshot 4](https://user-images.githubusercontent.com/19931977/38487618-e1f67fd6-3bf1-11e8-895b-80099060ddaa.png)

**Comment by ifedapoolarewaju** [comment]
ok can you please try to log out and log in again? Or did you do that already?

**Comment by Mwicigi** [comment]
Logged out and now my credentials dont work as i am logging in

**Comment by ifedapoolarewaju** [comment]
@Mwicigi what error do you get when you try to login?

I suspect this has to do with your connection, if not please try to log into instagram.com on your browser, and if you are unable to login still, then it means your password might have been changed, otherwise then it means instagram might be blocking igdm from connecting. Please let me know how this goes.

**Comment by Mwicigi** [comment]
Hi it seems like Instagram blocked the app because I havent changed my
password yet

**Comment by marioadisaputra6512** [comment]
why can't i enter my ig account ????

**Comment by marioadisaputra6512** [comment]
![map_tile](https://user-images.githubusercontent.com/42600489/44446659-e4e91180-a60f-11e8-8efb-8f62a065923b.png)

**Comment by marioadisaputra6512** [comment]
Kami Mendeteksi Upaya Masuk Yang Tidak Biasa
Android | Aug 21, 11:25PM
Jakarta, Indonesia

Untuk mengamankan akun Anda, beri tahu kami jika ini Anda.

**Comment by marioadisaputra6512** [comment]
tulisan nya begitu

**Comment by marioadisaputra6512** [comment]
itu pas saya cek
