### ISSUE TITLE
Improve suggestion

### ISSUE THREAD

**Issue by ckh95** [ifedapoolarewaju/igdm#134]
1. The direct message list only can show 20 persons, it is the design or bug? I hope it can show all the direct message box.
2. Message record only show 20 too.
3. The direct message requests are not shows in the apps when it's not apply already.
4. Could you add the function about searching the message record form direct message?
5. Also, I recommend add the button for download picture. In fact now have same function, the photo can pull out of windows and save in the pc, but it's not most convenience.

Thank You！

**Comment by chadleylyell** [comment]
Just mentioned some of these :)))
#164

**Comment by thevisionaire** [comment]
I would love to see these options too! Especially the message requests, more messages then 20, and ability to search messages. Happy to pay for a solution! My IG dms are out of control and I have no way to manage them
