### ISSUE TITLE
Cannot Unsend Messages

### ISSUE THREAD

**Issue by MariahISskinny** [ifedapoolarewaju/igdm#137]
This project is great. It has helped me a lot especially since I have not been able to retrieve my lost phone. Although it has some pros, one con that stands out to me is the inability to unsend messages on it like the phone version lets you. I have sent multiple uninteresting and irrelevant messages while being silly the spontaneously regretted it afterwards. I feel like this team should add this feature to make the experience in using the application more enjoyable.

-J

**Comment by chadleylyell** [comment]
I just mentioned this as well :)))
#164
