### ISSUE TITLE
IG:dm not working

### ISSUE THREAD

**Issue by rishabhdingliwal** [ifedapoolarewaju/igdm#147]
I am using Instagram Desktop Messenger on windows 7 and it has been working fine till now. But now suddenly it shows "sessionid" not found or doesn't exist. My instagram account is working fine and I have also tried re-installing the program but it's still the same problem. Please find a solution to it as soon as possible. I am also attaching a screenshot for your reference.
![untitled](https://user-images.githubusercontent.com/38527460/38987889-f83fbeba-43ee-11e8-99be-c290a77c601b.jpg)

**Comment by ifedapoolarewaju** [comment]
this issue is fixed for me now, can you please try again. Closing this

**Comment by IMSYAMAK** [comment]
I am using igdm but now no contacts of mine are being shown on the left side of the application ,and no message can be sent even after searching a user's name..Please help me with this problem as soon as possible.
![capture](https://user-images.githubusercontent.com/39824214/40833243-f418fbfc-65aa-11e8-8902-927045cc1e53.PNG)
