### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by alice1232** [ifedapoolarewaju/igdm#150]
My instagram DMs won't work at all and its pretty annoying to me

**Comment by shrenika-solanki** [comment]
same here how to fix this problem

**Comment by alejoloaiza** [comment]
same here "Instagram call checkpoint for this action!"

**Comment by chadleylyell** [comment]
Is it possible that your guys' accounts got locked by Instagram?

**Comment by alexmozzhakov** [comment]
Duplicate of #125

**Comment by alexmozzhakov** [comment]
@chadleylyell that's not an issue here

**Comment by MirzaUmar3211** [comment]
Instagram call checkpoint for this action!
Plz solve my problem

**Comment by cameronmck2000** [comment]
Found the problem, you need to go onto the instagram website because someone tried to log into your account and it put it in a checkpoint, causing this problem, all you need to do is change your password or say yes it was me when it asks you.

**Comment by Avatar4pro** [comment]
turn off 2f auth.
