### ISSUE TITLE
Cannot login to the IG:dm app!

### ISSUE THREAD

**Issue by krisiumreason** [ifedapoolarewaju/igdm#156]
Hello,
Can you please help me to solve an issue?
I wanna login to the app, I put username and password.
Two factor is OFF

I receive a message:
Cookie `sessionid` you are searching found was either not found or not valid!

What is a problem and how can i login?

Waiting for a solution.

Thank you!

**Comment by krisz011** [comment]
I also have this problem :(

**Comment by ifedapoolarewaju** [comment]
this issue is fixed for me now, can you please try again. Closing this

**Comment by krisiumreason** [comment]
Still cannot login.
What is a problem?
