### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by jacksonakim** [ifedapoolarewaju/igdm#161]
I can't log in help me pleaseee 
It says..Cookie `sessionid` you are searching found was either not found or not valid

**Comment by solangech** [comment]
Cookie sessionid you are searching found was either not found or not valid

**Comment by ifedapoolarewaju** [comment]
this issue is fixed for me now, can you please try again. Closing this

**Comment by jacksonakim** [comment]
I tried but nothing
