### ISSUE TITLE
Log-in issue

### ISSUE THREAD

**Issue by sonofthunder70** [ifedapoolarewaju/igdm#162]
When I try to log into Instagram, I can't get in. Apprently, the issue is: "Cookie "sessionId" you are searching found was either not found or not valid." I had no trouble getting in before and I don't remember changing anything on my computer. I looked on the site to see how to fix this problem, but it doesn't say. Can you fix this? Or have an idea of how I can log in???

**Comment by ifedapoolarewaju** [comment]
this issue is fixed for me now, can you please try again. Closing this
