### ISSUE TITLE
Can't log in due to "Cookie `sessionid` you are searching found was either not found or not valid!"

### ISSUE THREAD

**Issue by denarijpsma** [ifedapoolarewaju/igdm#165]
I just downloaden IG:dm on my laptop. I had it before, but I had some problems with my laptop so I re-installed windows. 

I tried to log onto my own account, but it sais: "Cookie `sessionid` you are searching found was either not found or not valid!"

I think this is because I was logged in on my previous windows, but I don't know how to solve this. 

Can you help me?

Edit: 

I now see a lot of issues that are "solved" with the same problem. But it still is not "solved" for me.

**Comment by paranoiasystem** [comment]
I have the same error

**Comment by Guilwim** [comment]
Same here

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed in the latest version https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.1
