### ISSUE TITLE
Error: getaddrinfo ENOENT i.instagram.com:443

### ISSUE THREAD

**Issue by gibmuq** [ifedapoolarewaju/igdm#168]
Error: getaddrinfo ENOENT i.instagram.com:443
I found this this message when i try to log in :(
Anyone can help me ?

**Comment by ilyaskamdeshi313** [comment]
rror: getaddrinfo ENOENT i.instagram.com:443
I found this this message when i try to log in :(
Anyone can help me ?

**Comment by wendyswaim** [comment]
Error: connect ECONNREFUSED 8.7.198.45:443
I found this message when I try to log in :(
Anyone can help me?

**Comment by clyde55** [comment]
Error: getaddrinfo ENOENT i.instagram.com:443
I found this this message when i try to log in :(
Anyone can help me ?

**Comment by ofSanjay** [comment]
Error: getaddrinfo ENOENT i.instagram.com:443

**Comment by GVytal** [comment]
Error: getaddrinfo ENOENT i.instagram.com:443 
Encontré este mensaje cuando intento iniciar sesión :( ¿ 
Alguien me puede ayudar?

**Comment by jakesterjung** [comment]
Error: getaddrinfo ENOENT i.instagram.com:443
same problem here and i just downloaded it, shouldhv been the newest updated version.
HELP PLEASE!
