### ISSUE TITLE
Minimize to system tray and others

### ISSUE THREAD

**Issue by seahindeniz** [ifedapoolarewaju/igdm#182]
Hi

I would like to suggest couple things because it is not necessary that the IG:dm can be visible at taskbar all the time. http://prntscr.com/jcojev

Also, some of menu items can be removed or hide some times like the Window menu is not necessary when window is not in fullscreen mode on Windows OS or other OS's. http://prntscr.com/jcojp2

Also resizing the users panel will be awesome! http://prntscr.com/jcoj0o

**Comment by traBolic** [comment]
Also, keeping the last session active and pasting image to input box from clipboard can be usefull.
