### ISSUE TITLE
Load All messages?

### ISSUE THREAD

**Issue by Clarkeyyy** [ifedapoolarewaju/igdm#199]
Hello!

Great product by the way.

I run social media for a business and was wondering if there was a possibility to view every single message? It looks like it only loads a limited amount of users. We have messaged a couple thousand and have difficulty finding people we have messaged before.

Thanks again for the app!

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.5.1 please visit the site http://igdm.me to download the latest version
