### ISSUE TITLE
Attatchments in IGdm

### ISSUE THREAD

**Issue by rishabhdingliwal** [ifedapoolarewaju/igdm#201]
Pictures or any other media are not being sent on DM. Nothing happens when you click open file and attach it. Also a lot of emoji's are not displayed instead squares are present. Is it beacuse of some graphic card or some resolution kind of problem on my desktop??

![untitled](https://user-images.githubusercontent.com/38527460/39955241-0f0357ea-55e9-11e8-80c8-130f0d5b2aa7.jpg)

**Comment by pdayvson** [comment]
My Deepin Linux also does not properly display someone emojis. There is probably no native support for all emojis.
