### ISSUE TITLE
IG:dm Login using Facebook Account

### ISSUE THREAD

**Issue by jpnaval03** [ifedapoolarewaju/igdm#206]
Good day! Since before, i created my instagram account using my IG App on my phone. As I created it, I used "Create Account Using Facebook". As i tried to login on IG:dm, it requires only two things to login-username/email and password. I can't login to the app because i dont really have instagram account because i used a third party app to login in instagram which is facebook. Please help me solve this issue. I really want to view my DMs on Instagram on my PC. Thank you so much and more power!

**Comment by nitrodragon** [comment]
@jpnaval03 Had the same issue as I was downloading it. I just went into IG and reset my password, then used the new password onto IGDM. Been working perfectly fine ever since.

**Comment by ali22222222222** [comment]
Hello a method you have ? which I  vcf contacts through  computer in Instagram To access  

I can not speak English properly Sorry
Can you help me with my Gmail address?
mohammasnk57@gmail.com
Grateful

**Comment by jackie-d** [comment]
The @nitrodragon answer works.
Just follow the procedure from instagram website at https://www.instagram.com/accounts/password/reset/

or from the app.

Cheers :)
