### ISSUE TITLE
Formatting of messages

### ISSUE THREAD

**Issue by g8f6r4e7x2** [ifedapoolarewaju/igdm#21]
The app is not formatting line breaks properly.
Also unable to compose multiline messages. 
Copying and pasting from notepad breaks the formatting too.

Thanks for the great app

**Comment by ifedapoolarewaju** [comment]
thank you for reporting. Will work on this

**Comment by ifedapoolarewaju** [comment]
@g8f6r4e7x2 this feature has been implemented. You may now type the `shift` + `Enter` keys to insert a newline in your messages. :)

Please visit https://ifedapoolarewaju.github.io/igdm/ to download, or if you are running the windows/mac versions, you can simply start the version you have and it would update itself :)

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.1.0)

**Comment by g8f6r4e7x2** [comment]
@ifedapoolarewaju Thank you for the update. I am using the windows version but it's not updating itself. I'm downloading the new setup file right now
