### ISSUE TITLE
Malware in this program?

### ISSUE THREAD

**Issue by propolisor** [ifedapoolarewaju/igdm#211]
My Instagram account was hacked (for the first time ever) shortly after (unsuccessfully) trying this program for the first time. The password of the e-mail account associated with it (which I also enter in using the same browser) was unaffected, as were the other accounts and programs I use on my computer, leaving this program (in which I entered only my Instagram login info and nothing else) as the primary culprit. Is it possible that malware has slipped into the binaries of this program?

**Comment by propolisor** [comment]
I downloaded it from that site and the binary came from Github's servers.

**Comment by Mozoloa** [comment]
Same situation, downloaded from the website, got my insta hacked a few hours later.

**Comment by Evoah** [comment]
Well thats bad to hear, i just installed it and use it for my business account, lets see if i get hacked too

**Comment by ifedapoolarewaju** [comment]
@propolisor @Mozoloa how exactly do you mean your insta account was hacked? What happened to the account after you tried to login?

**Comment by propolisor** [comment]
@ifedapoolarewaju The password was changed (with an e-mail sent notifying me of this) and my old password was invalid. I had to change it back via e-mail to regain control of the account.

**Comment by ifedapoolarewaju** [comment]
the website now enforces https. https://igdm.me
