### ISSUE TITLE
Wrong group messages

### ISSUE THREAD

**Issue by ifedapoolarewaju** [ifedapoolarewaju/igdm#22]
sometimes when sending a message to an already existing group on my chat lists, it creates a new chat room and sends the message there. The expected behavior is to send the message to the already existing chat and not create a new one

**Comment by shaun040** [comment]
I can confirm this happens to me as well. Tested on latest versions on Windows and OSX

**Comment by nullbones** [comment]
is there any fix for it?

**Comment by nullbones** [comment]
I'm on Ubuntu 16.04

**Comment by ifedapoolarewaju** [comment]
fixed [here](https://github.com/ifedapoolarewaju/igdm/commit/ee06584b322ec4c56d1dd7566e8f3bb31bd6bd6a)
