### ISSUE TITLE
Users Not Following Back Not Working

### ISSUE THREAD

**Issue by UptownPhotography** [ifedapoolarewaju/igdm#220]
The "Users Not Following Back" feature is Not Working on my PC (windows 8.1). When I click on it the screen does nothing and does not populate the screen with people that are not following me. Never had this issue before. I tried closing the program and re-opening it, but still does not work. I can still DM OK. Thanks in advance..........Philip

**Comment by paper-boi** [comment]
hi guys, same happen to me on Windows 10. cheers,Rik

**Comment by ifedapoolarewaju** [comment]
this is now fixed in version 2.4.2
