### ISSUE TITLE
DM Load Limit

### ISSUE THREAD

**Issue by Evoah** [ifedapoolarewaju/igdm#224]
Hello,  

i just foudn your app and as great as it is i use it for business purposes, it just loads up the recent 10-20 DMs which makes it almost unusable.

Hope this will be fixed very soon

**Comment by cdrop** [comment]
I think it might be a limit to the API, not his application.

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.5.1 please visit the site http://igdm.me to download the latest version
