### ISSUE TITLE
cannot scroll to older messages

### ISSUE THREAD

**Issue by ionescueduard** [ifedapoolarewaju/igdm#230]
i'm unable to load older messages in a conversation. there is a limited scrolling up.

**Comment by xerox4** [comment]
please fix it as soon as possible

**Comment by SimonVanacco** [comment]
Fixed by commit "44863b711998b4b01e4ce233f5bdc64dfaa042a8"
Launch IgDM and let the AutoUpdater do the job, you'll get the new feature ;)

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.5.1 please visit the site http://igdm.me to download the latest version
