### ISSUE TITLE
Linux Version keeps Daemon process(?) running after closing the app

### ISSUE THREAD

**Issue by Jpfonseca** [ifedapoolarewaju/igdm#231]
Opened the application and closed it and the process(1) kept running. 
Upon starting the app again, another process(2) will spawn, and both of them will continue "working" until i kill them .

**Comment by breakfast1** [comment]
Same here.

**Comment by marcindomanski** [comment]
And same here, Ubuntu 18.04, version 2.6.5. Closing the main window simply does not exit the app. In fact, a few igdm processes are left running in background.

**Comment by baptx** [comment]
@ifedapoolarewaju this issue is not fixed and it looks like there is no duplicate open, why did you close it?
To kill the app process on Linux, we need to run the app from the command line and press Control+C to close it or to use a command like "killall igdm".
