### ISSUE TITLE
Message List Truncated

### ISSUE THREAD

**Issue by uzorjchibuzor** [ifedapoolarewaju/igdm#232]
I am using a Linux Version of the software.
My message list is longer than that when I opened in on my phone. This issue is after the app automatically updated itself (without consent). 

![screenshot from 2018-05-31 10-17-48](https://user-images.githubusercontent.com/32690770/40787577-f44917e6-64bb-11e8-8025-eacc8f9863f5.png)

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.4.3 please visit the site http://igdm.me to download the latest version
