### ISSUE TITLE
i cant see anyone im messaging.

### ISSUE THREAD

**Issue by lizardrockband** [ifedapoolarewaju/igdm#235]
its justnot doing anything. im probably gonna redownload it but help.

**Comment by anesthetize48** [comment]
same here

**Comment by paolasmit61** [comment]
same here

**Comment by tengokutyrant** [comment]
same here. I thought it was because I closed the app while a current message was still in progress of sending in one of my chats. I uninstalled/reinstalled but nothing seems to help.

**Comment by lizardrockband** [comment]
i didnt think this was such a common thing. i ended up just installing the app on my computer bc i have windows 10 but yeah they all just disappeared. i dunno what to do either/

**Comment by lizardrockband** [comment]
the convos dont get erased bc i checked on insta and theyre still there but on this app it just made then disappear

**Comment by primeministerjoshua812** [comment]
Jpfonseca Do you know how to solve this issue or not?

**Comment by Jpfonseca** [comment]
@primeministerjoshua812 I just discovered this project yesterday. I used the application one time and found a bug unrelated to this current issue. 
I am not fixing a issue, if I don't know how the application works :unamused: ...

**Comment by tomoyuk1** [comment]
Same here #268  -_____-

**Comment by ifedapoolarewaju** [comment]
I'll investigate this issue, sorry for the problems

**Comment by kaposztaserzsebet** [comment]
I got the same problem it's so annoying I just want to message my friends
If you have it on PC you can download Blustacks app player, it might work for you but didn't work for me :(

**Comment by iejamsaleh** [comment]
@kaposztaserzsebet bluestacks doesn't work for me as well, my phone is currently not working and IGDM is the only software that works for us (is there any other software?), and the only way I can message my IG friends . Hope this issue will be resolved very soon.  Thank you in advance @ifedapoolarewaju

**Comment by iejamsaleh** [comment]
![igdm not working](https://user-images.githubusercontent.com/39817887/40829786-1ba154ba-65b7-11e8-8801-0772b85cf0f2.PNG)

**Comment by Jpfonseca** [comment]
Pls refer to #238

**Comment by Jpfonseca** [comment]
@ifedapoolarewaju I can help you sorting the issues, if you want.

**Comment by sherrytaimur** [comment]
i also have the same problem,please help!

**Comment by sherrytaimur** [comment]
@Jpfonseca do u know how to resolve this problem?

**Comment by ellaaaaaaaaa** [comment]
is anyone solving this problem? is this gonna be fixed soon?? like within the day

**Comment by huskymud44** [comment]
god so help us fix it please

**Comment by Beevix** [comment]
The owner commented there and said he is going to investigate now he deleted the comment :))))

**Comment by OpenMindOfficial** [comment]
i've found the problem, is into the instagram-private-api that if u go to the issue section there is an update on instagram apis that broken the module, [#497](https://github.com/huttarichard/instagram-private-api/pull/497) u've to run an update made by an user, i'm sorry for my english, it's my first post on github ahah

**Comment by OpenMindOfficial** [comment]
ps:i've updated and my igdm is running good

**Comment by cregamens** [comment]
> i've found the problem, is into the instagram-private-api that if u go to the issue section there is an update on instagram apis that broken the module, #497 u've to run an update made by an user, i'm sorry for my english, it's my first post on github ahah
Can you explain it just a bit better pls ?? 
thnks

**Comment by merve2001** [comment]
i hope it works how can i update it

**Comment by Beevix** [comment]
@OpenMindOfficial  can you explain?

**Comment by merve2001** [comment]
@OpenMindOfficial 
how can i update it i cant see anyting

**Comment by merve2001** [comment]
i found how to update it but it says windows 7 and above is required idk what to do @OpenMindOfficial @Beevix

**Comment by sherrytaimur** [comment]
how can i update?there is no sign of update

**Comment by merve2001** [comment]
@sherrytaimur type igdm.me update on internet and you come to a site where it can be downloaded

**Comment by Beevix** [comment]
@merve2001 and r u goin to tell how?

**Comment by sherrytaimur** [comment]
@merve2001 its still not working

**Comment by merve2001** [comment]
@Beevix @sherrytaimur go to this http://igdm.software.informer.com/2.3/ and start the downloud

**Comment by Beevix** [comment]
@merve2001 2.3 doesnt work. you have to install 2.2

**Comment by Beevix** [comment]
And its actually no update .. its downgrade

**Comment by Beevix** [comment]
and it requires 64bit

**Comment by nemanjan00** [comment]
From what I see, author of this tool has fixes for instagram-private-api applied in his own fork, so, it should work now.

**Comment by Beevix** [comment]
yea it just updated and its working

**Comment by ifedapoolarewaju** [comment]
It's all fixed now. Please update to the latest version on the site http://igdm.me  Sorry for the problems guys

**Comment by ifedapoolarewaju** [comment]
@Jpfonseca thank you for the effort in preventing scattered duplicates of issues 🙏

**Comment by merve2001** [comment]
it doesnt work by me whyy?

**Comment by merve2001** [comment]
i have windows 7

**Comment by OpenMindOfficial** [comment]
sorry guys, i was away from home, u've to clone the repo 2.4.2 normally, npm install into the folder but before npm start  u've to run 'npm i https://github.com/nemanjan00/instagram-private-api.git\#patch-1', it's not branched but it's working fine for me

**Comment by OpenMindOfficial** [comment]
sorry guys for te second time ahah i haven't readed the messages, i will download the update

**Comment by ifedapoolarewaju** [comment]
@merve2001 yes download for windows here https://github.com/ifedapoolarewaju/igdm/releases/download/v2.4.3/IGdm-Setup-2.4.3.exe

**Comment by baptx** [comment]
@ifedapoolarewaju I was not able to see my messages between 2 test accounts until I searched the username of the test account that sent the messages. This is a serious problem since people will not always know in advance the username that will send them a message. I tested the version 2.5.1 that was shared here: https://github.com/ifedapoolarewaju/igdm/issues/349#issuecomment-396568474
So it looks like this issue is not fixed yet in the latest version? Should we reopen this issue or create a new one?

**Comment by nemanjan00** [comment]
There is hidden inbox for people you are not following... 

It is on top of the inbox, to the right...

**Comment by baptx** [comment]
@nemanjan00 I did not see anything on the top right of the inbox, the user interface looks like these screenshots: https://github.com/ifedapoolarewaju/igdm/pull/87
Do you have a screenshot example?

**Comment by nemanjan00** [comment]
I am talking about mobile interface

**Comment by baptx** [comment]
@nemanjan00 I don't use any mobile version. So on IGDM desktop version, there is no way so see messages of people unless we send them also a message? cc @ifedapoolarewaju

**Comment by ifedapoolarewaju** [comment]
@baptx do you follow those test accounts on IG? Maybe the messages were received as `DM requests`? IG:dm does not display DM requests. You have to approve the request on the mobile app first.

However, if these users are those that you already follow on instagram, then you should see their messages on your list (on the left)

**Comment by baptx** [comment]
@ifedapoolarewaju no, the 2 test accounts did not follow each other. I don't use Instagram mobile app since I don't have Android or iOS (on mobile, I only use SailfishOS with open source apps).
Do you plan to add the feature to display DM requests? I guess I should create a different issue for this so people can see it and can contribute to your project if they are interested?
