### ISSUE TITLE
My chats ALL disappeared 

### ISSUE THREAD

**Issue by tengokutyrant** [ifedapoolarewaju/igdm#236]
I was in the middle of sending a text when i accidentally closed the app, upon opening it again...all my chats were gone and now new messages refuse to come send.

Please help me with this issue.

**Comment by NickPapiGoat** [comment]
same thing happened to me and im upset :(

**Comment by tengokutyrant** [comment]
damn this sucks ass. although i'm grateful it wasn't my dumbass for crashing the app it still sucks nonetheless.... smh. hopefully the team fix it.

**Comment by Jpfonseca** [comment]
same as #235
