### ISSUE TITLE
BIG BOY IT BROKE

### ISSUE THREAD

**Issue by Nathan398** [ifedapoolarewaju/igdm#238]
heyyy, so my messages aren't working. They won't show up. Fix

**Comment by Jpfonseca** [comment]
same as #236

**Comment by Jpfonseca** [comment]
Pls read the previous issues before creating new ones.

**Comment by Nathan398** [comment]
say that to the other 50 people with the same issue. How am I suppose to chat with hot babes now? Grandmas internets going to waist. Cheeze Napoleon.
