### ISSUE TITLE
Instagram DMS

### ISSUE THREAD

**Issue by beingnaomi** [ifedapoolarewaju/igdm#249]
My messages aren't showing up

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by beingnaomi** [comment]
oh kay,, u plan on fixin it or nah ?

**Comment by Jpfonseca** [comment]
I am not the developer. I'm receiving all of these issues cause someone wants to use the app.  I am a subscriber of the mailing list and I am just trying to sleep
