### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by qisoko382** [ifedapoolarewaju/igdm#253]
My conversations do not show up anywhere. What should I do? (I can´t select a conversation)

**Comment by tengokutyrant** [comment]
same here bro. it seems everyone who uses the app on PC is having the same problem. hopefully it gets cleared up soon. *crossed fingers* you're not alone

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.
