### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GitHurb** [ifedapoolarewaju/igdm#254]
I cannot see any messages and also cannot message other people. Please, Help me. Thank You.

**Comment by tengokutyrant** [comment]
same here dude, you're not alone. many are experiencing the same problem as you. hopefully they clear it up soon.

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by mexvhn3m** [comment]
![Снимок](https://user-images.githubusercontent.com/49337906/55668059-f2849c00-586c-11e9-9153-916bb33b03d0.JPG)
windows 10
