### ISSUE TITLE
No me muestra los chats

### ISSUE THREAD

**Issue by diego3215** [ifedapoolarewaju/igdm#260]
Tengo un problema, al iniciar el programa me inicia sesión en mi cuenta de instagram pero no me muestra los chats que realizo ni me deja hablarle a nadie...

Por favor arreglen este problema utilizo mucho la aplicación.

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by Josedj01** [comment]
No me deja escribirle a la persona correspondiente, a veces que escribo se envía a otra persona y no me deja ver los mensajes que me enviaro, por favor ayuda.
