### ISSUE TITLE
I found a mistake in the app IG:dm

### ISSUE THREAD

**Issue by Sebastian1127** [ifedapoolarewaju/igdm#267]
Okey.

I want to talk with my girlfriend, so i use this app for do that. Today in the afternoon, i talked with her and finally i closed the app. When i wanted to talk with her again i could not appear the conversations. so, what can i do for solve this problmes?.
Thanks

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by Sebastian1127** [comment]
Thanks. i'll see that. if i found something i will put the solution in other answer in this forum page
