### ISSUE TITLE
IG DM on Laptop Not Show list chat

### ISSUE THREAD

**Issue by tomoyuk1** [ifedapoolarewaju/igdm#268]
Hi,

I want to complain about my IG DM on laptop.
When I successfully installed it, list chat doesn't appear as attached.
So, is there a trouble or what?
I already uninstall and installed it again but it still doesn't appear
Please give me an advice and answer.

Regards,
Tom
![ig dm](https://user-images.githubusercontent.com/39818830/40820913-a6d74802-658d-11e8-971c-5ce2fce4d773.jpg)

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by kaposztaserzsebet** [comment]
The EXACT same thing happened to me, I don't get what is going on but I'm so annoyed :(

**Comment by tomoyuk1** [comment]
Yeaah finally, the apps has been fixed, thank you so much ^_^
