### ISSUE TITLE
IG:dm isn't working right

### ISSUE THREAD

**Issue by MicJesus** [ifedapoolarewaju/igdm#269]
When I go onto IG:dm and I sign into my account I can't see any of my followers or people that I have been recently messaging at all. Then when I go to the search bar and type in one of the peoples names that I've been texting for a while they pop up, but for only like half a second. Also when I go to try to message one of the people that I've been texting for a while the message that I sent won't send at all.

In summery, no one appears on my DM list and when I go to search one of the peoples names that I've been texting for a while they only pop up for half a second, and when I go to try to text them my message doesn't send at all.

Please fix this issue asap cause it's driving me nuts.
Thank you :)

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by MicJesus** [comment]
Thank you for fixing this problem. I genuinely appreciate it :). And if it
wasn't you who fixed it; thank you from spreading the word about this issue
so that it would reach those who could/can fix it.

Thank you.
