### ISSUE TITLE
instachat 

### ISSUE THREAD

**Issue by dhosheena** [ifedapoolarewaju/igdm#270]
i am not getting my messages

**Comment by 8iijr** [comment]
me too. can this issue be fixed please.

**Comment by 8iijr** [comment]
isn't there somone that's able to fix to it.

**Comment by merve2001** [comment]
i have the same problemmm

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.

**Comment by dhosheena** [comment]
what's wrong with this man ...they are not even making an effort to solve the problem !!!
