### ISSUE TITLE
Chats not loading

### ISSUE THREAD

**Issue by prashanth222000** [ifedapoolarewaju/igdm#273]
![capture](https://user-images.githubusercontent.com/39819755/40822174-97ebd768-6588-11e8-83ac-8366ac1e601f.JPG)
My screen appears like this.. and if I try to search a person's name and send a message to them it doesn't work either..

**Comment by merve2001** [comment]
i have the same problem

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.
