### ISSUE TITLE
IGDM no side icon

### ISSUE THREAD

**Issue by jyyen** [ifedapoolarewaju/igdm#275]
Hi
I'm using IGdm 2.4.2, and seems very suddenly I was left with no side icon and can't send message.
![screenshot 2018-06-01 14 22 16](https://user-images.githubusercontent.com/4451864/40824774-edcead94-65a7-11e8-8a60-972af79eb0ab.jpg)

**Comment by Jpfonseca** [comment]
same as #235 . Pls read the previous issues before creating new ones.
