### ISSUE TITLE
IG:dm not showing my messages

### ISSUE THREAD

**Issue by kaposztaserzsebet** [ifedapoolarewaju/igdm#278]
I downloaded IG:dm about 3 weeks ago, I have messaged people quite a lot and today I opened the app and all my messages were gone, they wouldn't show. I tried reinstalling the app and it didn't work at all. I logged out and in a million times, my messages are still not showing. I tried updating the app, I thought maybe that was the reason why it wasn't working but it's STILL not working. I don't know what's going on, I have Windows 8.1 on my laptop. 
Thanks for your help

**Comment by Jpfonseca** [comment]
Refer to #235
