### ISSUE TITLE
IGL:

### ISSUE THREAD

**Issue by ayushjadvani** [ifedapoolarewaju/igdm#280]
Hello Team,
My account messages is not open and no any account see in the IG:dm.
My account name is ayushjadvani and second account name is ayush_jadvani..

Thank you

**Comment by iejamsaleh** [comment]
Refer to #235. Everyone is having the same problem

**Comment by ayushjadvani** [comment]
Hello Team,
This problem permanent???
Please solve this problem.

Thank you

**Comment by ayushjadvani** [comment]
Hello Team,

Other application for instamessege ???
Say me please

Thank you
