### ISSUE TITLE
Complaint for not being able to view my messages.

### ISSUE THREAD

**Issue by Someone-somewhere-under-the-sky** [ifedapoolarewaju/igdm#285]
Hi! I am an IGDM user. I love using IGDM. It helped me connect with many people. Whenever I log in and open it I can view the messages which I have either recieved or send. Unfortunately, today when I opened it I am unable to see them. I assure you that I haven't deleted even a single message. 

It is very important for me to see those messages right now. I will be highy obliged if you read the above problem faced by me and act as soon as possible.

Thanking You,
Yours faithfully,
User.

**Comment by Jpfonseca** [comment]
Refer to #235. Everyone is having the same problem
