### ISSUE TITLE
igdm not working properly

### ISSUE THREAD

**Issue by mol10** [ifedapoolarewaju/igdm#287]
so the program was working absolutely fine 2 days ago
and now i am unable to send any messages and i cant even see the chat heads.please resolve this asap.
thanks.ia ma attaching a screenshot of the same
[New Microsoft Office Word Document.docx](https://github.com/ifedapoolarewaju/igdm/files/2061920/New.Microsoft.Office.Word.Document.docx)

**Comment by Jpfonseca** [comment]
Refer to #235. Everyone is having the same problem
