### ISSUE TITLE
Contacts aren't there 

### ISSUE THREAD

**Issue by Beeoobeeooomikumiku** [ifedapoolarewaju/igdm#289]
The contacts on the left side were there when I first used it, suddenly they're gone. Please fix this?
![no contacts](https://user-images.githubusercontent.com/39827160/40835061-472f980a-6547-11e8-95e0-7ad505aad6a8.PNG)

**Comment by soumyadhingra** [comment]
I also have the same issue.

**Comment by Jpfonseca** [comment]
Refer to #235 . Everyone is having the same problem
