### ISSUE TITLE
Error: connect ETIMEDOUT 203.98.7.65:443

### ISSUE THREAD

**Issue by ejcoo** [ifedapoolarewaju/igdm#298]
Hi there, I try to run the the IGdm, but it is said **_Error: connect ETIMEDOUT 203.98.7.65:443_** after I write the user name and password, what should I do?

**Comment by Jpfonseca** [comment]
Refer to #235 . Everyone is having the same problem

**Comment by wendyswaim** [comment]
same as me, have that issue happened

**Comment by jeanqq4** [comment]
Me too.

**Comment by JackLyao1022** [comment]
Cant this issue be solved? I met this problem as well.
