### ISSUE TITLE
send media

### ISSUE THREAD

**Issue by ifedapoolarewaju** [ifedapoolarewaju/igdm#3]
Users should be able to send images/videos to recipients.

**Comment by vampire337** [comment]
There is a button to upload a picture, and it lets you select a picture file, but nothing happens.

**Comment by ifedapoolarewaju** [comment]
The image upload experience has now been improved on [version 2.6.0](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.6.0)

**Comment by baptx** [comment]
@ifedapoolarewaju it is possible to send images but not videos. Another missing feature compared to the official mobile app is to send an audio recording.
Should we reopen this issue for the video and audio or create 2 separate issues?

**Comment by ifedapoolarewaju** [comment]
hi @baptx we could create a separate issue for this indeed.

**Comment by baptx** [comment]
Hi @ifedapoolarewaju, I created a new issue for sending video and audio. By the way, can you reopen issue 519 that was closed by mistake?
