### ISSUE TITLE
Two-Step Authentication login is unhandled

### ISSUE THREAD

**Issue by ghaith96** [ifedapoolarewaju/igdm#30]
if the account you are trying to login with has 2FA enabled, no response is displayed, and nothing happens.
instead of using private api, you may just load instagram login page, and collect/save the cookies after a successful login.

**Comment by ifedapoolarewaju** [comment]
Thank you for reporting this 👍 

I'll look into this. But also feel free to send a PR, It would be much appreciated. 🙂

**Comment by LukyVj** [comment]
Same issue..

**Comment by Jostino** [comment]
Any other news about?

**Comment by ifedapoolarewaju** [comment]
Hi @Jostino , unfortunately there's no solution to this yet. I have tried to implement this today, but an implementation needs to be updated in the [depended library](https://github.com/huttarichard/instagram-private-api/).

A current WORK AROUND would be to:
 1. disable two-step authentication
 2. login to igdm
 3. re-enable two-step authentication

The instagram API would then recognize your IGdm device from that point on, and you would not be required to enter the 2-step verification code even if you logout and then log back in.

**Comment by drigio** [comment]
@ifedapoolarewaju Hey can we not have our own forked repo of instagram-private-api in which we can make changes to and implement in it?  BTW, I have just started electron and node.js and so I'm a complete beginner with many doubts. :)

**Comment by dzikoysk** [comment]
![obraz](https://user-images.githubusercontent.com/4235722/61724607-9cc9f600-ad6e-11e9-9694-5e4fe421e7b6.png)

Any update?

**Comment by ghaith96** [comment]
Hey, thanks for the bump @dzikoysk 😁.
I checked latest version of the library, looks like they added 2FA support recently.
After skimming the code, i was able to determine the api call and the parameters.
The only thing that we are missing is the csrf token that is sent with the original login request.
Our current version returns the body of the response as the error object, which contains the field two_factor_required that we check and display that the user has 2FA enabled message.

i think we have few options :- 
1. Upgrade to the latest version (V1.21.1) of the library, which i suppose is not backward compatible with our version (0.7 i believe).
1. As @drigio mentioned, we can maintain our own forked repository of the library and implement the 2FA login.
1. Override some methods to return the required additional data. (not sure tho ! 🤔)

There is many outdated dependencies that should be upgraded, at least for security/performance reasons, which we can do on separate branch.

what do you think @ifedapoolarewaju ?

**Comment by ifedapoolarewaju** [comment]
Hi @ghaith96 I think we can try with option `3`. The csrf token is probably present in the `session` object, we just can't access at the point the error is triggered. I suggest we do something similar to [how it's done for ChallengeRequired](https://github.com/ifedapoolarewaju/instagram-private-api/blob/custom/client/v1/request.js#L318-L319), where the session object is passed to the error object (e.d TwoFactorRequiredError), and it is used to make 2FA related requests. Does this make sense to you?

**Comment by ifedapoolarewaju** [comment]
@ghaith96 Also, thank you for chiming in on this! ❤️

**Comment by ghaith96** [comment]
This makes perfect sense @ifedapoolarewaju and that is exactly what i need, thank you !
I'd like to give it a shot if possible, i'll do pull requests on both repositories with the necessary changes.
Btw, I have vscode auto-formats my code upon saving the current file, I noticed that it added a bunch of spaces in various places, I was wondering if there is any  code style/contribution guidelines ?
