### ISSUE TITLE
haven't been able to log in, times out

### ISSUE THREAD

**Issue by dianapickens** [ifedapoolarewaju/igdm#302]
![timed out](https://user-images.githubusercontent.com/39830357/40840097-47b7e60c-6573-11e8-8068-7047c8fcc2c7.JPG)

**Comment by dianapickens** [comment]
@ifedapoolarewaju This issue has not been fixed. I am still having it on my PC/windows computer. no issue on my macbook.

**Comment by dianapickens** [comment]
@ifedapoolarewaju  it is working now.

**Comment by Lecoin77** [comment]
How did you fix the problem?
