### ISSUE TITLE
two-step verification

### ISSUE THREAD

**Issue by NumbGrip** [ifedapoolarewaju/igdm#31]
app doesn't seem to work if 2-step verification is active since there is no prompt to insert code

**Comment by alibekch** [comment]
confirm, the app doesnot access the 2-step verification request.

**Comment by Jostino** [comment]
There is already an issue about

here is the link: https://github.com/ifedapoolarewaju/igdm/issues/30

**Comment by ifedapoolarewaju** [comment]
closing this as duplicate
