### ISSUE TITLE
Problem , my chat got empty

### ISSUE THREAD

**Issue by asd312** [ifedapoolarewaju/igdm#314]
Hello, on my IG:dm program all chats got cleared. And even If i write to a new person now - there is no chat keeped, it always shows me that i have 0 chat opened, no matter if i try to message new people.

Till now all was great with this program, i don't know what happened, can you help me please? Thank you!

**Comment by huskymud44** [comment]
i have the same problem i cant find anything to trouble shoot it tho...

**Comment by asd312** [comment]
Yeah.. Do you have any idea how we can fix this?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-06-01 18:15 GMT+03:00 huskymud44 <notifications@github.com>:

**Comment by huskymud44** [comment]
no i have no freaking idea
>>
.

**Comment by Jpfonseca** [comment]
Refer to #235 . Everyone is having the same problem
