### ISSUE TITLE
IG:dm isn't working?

### ISSUE THREAD

**Issue by tres-lesbien** [ifedapoolarewaju/igdm#315]
So I've tried logging in and out multiple times, but whenever I do log in, it doesn't show any of the icons for my conversations or show any indication of them being there, like letting me hover over them or anything. I even uninstalled it from my computer and reinstalled it, and it still isn't working. I'll attach a screenshot too.
![untitled](https://user-images.githubusercontent.com/39834554/40847346-1ff90daa-658a-11e8-8a6b-031aaa23643b.jpg)
I hope that works. Thanks!

**Comment by huskymud44** [comment]
same for me there are like six other conversations about this.

**Comment by Jpfonseca** [comment]
Refer to #235 . Everyone is having the same problem
