### ISSUE TITLE
IG:dm messages not showing up on PC 

### ISSUE THREAD

**Issue by myrojones** [ifedapoolarewaju/igdm#317]
For some reason I cant see my messages on the IG:dm app on my computer. it was working fine yesterday and has been prior but now it isn't showing anything.

**Comment by Jpfonseca** [comment]
Refer to #235 . Everyone is having the same problem

**Comment by Divya2198** [comment]
yes i do . after loging in i can't even see my contact list or either previous messages

**Comment by myrojones** [comment]
I had to create a GitHub account just to post this and after I did I saw I wasn't the only one.

**Comment by kalisettysowmya** [comment]
I cant see my messages on the IG:dm app on my computer. it was working fine yesterday and has been prior but now it isn't showing anything.
