### ISSUE TITLE
igdm 

### ISSUE THREAD

**Issue by sherrytaimur** [ifedapoolarewaju/igdm#318]
the messsages are cleared,why is that happeneing?

**Comment by OpenMindOfficial** [comment]
u've to update to 2.4.3

**Comment by merve2001** [comment]
where can i find it @OpenMindOfficial

**Comment by Jpfonseca** [comment]
[Version 2.4.3](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.3)
