### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by meth246** [ifedapoolarewaju/igdm#319]
Hello, when I enter the application I do not see the messages sent to different users, and I have reinstalled the application several times and nothing works

**Comment by merve2001** [comment]
@meth246 i have the same problemm

**Comment by Jpfonseca** [comment]
Read issue #235  . The code was updated . You should download the new version now.

**Comment by ifedapoolarewaju** [comment]
Please Install the latest version from http://igdm.me
