### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by juandwisatya** [ifedapoolarewaju/igdm#320]
Please fix this issue, because i've been waiting for 3 hours and the page is still blank. What happen to this app?

**Comment by merve2001** [comment]
@juandwisatya sameeee

**Comment by Jpfonseca** [comment]
Read issue #235  . There's a update on the way. You should download the new version now.

**Comment by Jpfonseca** [comment]
[Version 2.4.3](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.3) @merve2001  @juandwisatya

**Comment by merve2001** [comment]
@Jpfonseca is it avaible for windows 7 ?

**Comment by ifedapoolarewaju** [comment]
Please Install the latest version from http://igdm.me
