### ISSUE TITLE
IGDM login not working

### ISSUE THREAD

**Issue by maheenxmirza** [ifedapoolarewaju/igdm#322]
when i try to log into my account, it doesnt let me, please fix this asap. love igdm smm

**Comment by Beevix** [comment]
you sure the login name and password are correct?

**Comment by shanza-anwar** [comment]
When I login my account all conversation are deleted & I can't send messages to my friends.. & it shows javascript error
please fix this

**Comment by fabiofdsantos** [comment]
@shanza-anwar
What's the javascript error? It's working properly here.
