### ISSUE TITLE
igdm application is not showing the chat list

### ISSUE THREAD

**Issue by tafadzwa13** [ifedapoolarewaju/igdm#326]
![capturedc](https://user-images.githubusercontent.com/39853435/40873038-af5240e8-6661-11e8-892d-53e623b6cb99.PNG)

**Comment by Arwwaaa** [comment]
sameeeeee

**Comment by Jpfonseca** [comment]
There's a new version of the application (2.4.3)

**Comment by Jpfonseca** [comment]
Refer to #235

**Comment by ifedapoolarewaju** [comment]
Please Install the latest version from http://igdm.me
