### ISSUE TITLE
how to download the new version

### ISSUE THREAD

**Issue by Arwwaaa** [ifedapoolarewaju/igdm#327]

**Comment by Jpfonseca** [comment]
Head  [here](https://github.com/ifedapoolarewaju/igdm/releases) . And stop creating new issues for the same problem. Download the last version (currently it's 2.4.3)

**Comment by Arwwaaa** [comment]
oh thanks

**Comment by Jpfonseca** [comment]
@Arwwaaa  btw , if you can, close the issues you brought up .
