### ISSUE TITLE
Can't see my Instagram messages

### ISSUE THREAD

**Issue by MusiFlo** [ifedapoolarewaju/igdm#328]
For some reason my Instagram DM are missing. 
![screen shot 2018-06-02 at 3 53 39 pm](https://user-images.githubusercontent.com/39860045/40880355-33fbfde6-667d-11e8-91e7-7414da56e81f.png)

**Comment by Jpfonseca** [comment]
See #235

**Comment by Jpfonseca** [comment]
Download latest version

**Comment by ifedapoolarewaju** [comment]
Please Install the latest version from http://igdm.me
