### ISSUE TITLE
IgDM not working

### ISSUE THREAD

**Issue by ishhraq** [ifedapoolarewaju/igdm#331]
its not working. i cant see any chats/

**Comment by SimonVanacco** [comment]
Can you tell me what OS you are on? 
What is you IgDM version?

**Comment by janak6625** [comment]
it's not working for me either since 3-4 days, and I report an issue but no one reply to me. 
I am using windows 10 Enterprise, i7 16GB ram

https://snag.gy/JOR41E.jpg
