### ISSUE TITLE
Instagram call checkpoint for this action

### ISSUE THREAD

**Issue by Danielaoxance** [ifedapoolarewaju/igdm#344]
I am from Argentina and I am using a translator to ask for help. I do not know what to do anymore, I need to answer my Instagram messages urgently from my computer.
When I want to sign in, it says Instagram call checkpoint for this action! Then I enter from my phone and say "Suspicious session" Have you been? And two options.
It was not me.
It was me.
Try several times to choose the "It was me" option but I want to log in to IGDM and again it says "Instagram call checkpoint for this action"
**HELP!! PLEASE**

**Comment by merve2001** [comment]
@Danielaoxance i have the same problem now

**Comment by baptx** [comment]
Same here, there should be a functionality to enter a code to verify our identity like Instagram web version is doing for suspicious connections (they send a confirmation code by email).
By the way, @merve2001 I guess it is better to do a thumbs up (upvote) if you can reproduce the issue, thumbs down would mean downvote.
