### ISSUE TITLE
IGdm 2.5.1 Not Starting Up

### ISSUE THREAD

**Issue by octocat8** [ifedapoolarewaju/igdm#347]
Hi so, background to the problem, I use ubuntu16.04 and I decided to launch v2.4.3 from the terminal.
After the autoupdater window closed and I saw this line in the terminal "Install: isSilent: false, isRunAfter: true" I waited, then opened a new terminal and tried to run the AppImage.
I saw the following error in Terminal and no other visual feedback from the app.

module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-2PkHVko/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

Did I cause this, or is this from the code?

Side note: I also use Ubuntu 18.04, the same thing happened there as well. I tried a fresh download from the site and install but no, same error message in terminal

**Comment by ifedapoolarewaju** [comment]
it's most likely an issue from how the appImage was packaged. Can you try and see if the [deb](https://github.com/ifedapoolarewaju/igdm/releases/download/v2.5.1/IGdm_2.5.1_amd64.deb) works for you instead?

See [here](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.5.1) for all release binaries

**Comment by octocat8** [comment]
Thank you, the deb worked.
