### ISSUE TITLE
Linux - Error: Cannot find module '/tmp/.mount_IGdm-2GNftSR/resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by carloshpb** [ifedapoolarewaju/igdm#349]
Using Debian 9 - Xfce
After downloading the last version of igdm : IGdm-2.5.1-x86_64.AppImage
And also after giving permissions to it with chmod a+x IGdm-2.5.1-x86_64.AppImage

This error appear after tryint to open it on terminal : ./IGdm-2.5.1-x86_64.AppImage

module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-2GNftSR/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Comment by ifedapoolarewaju** [comment]
Can you try and see if the [deb](https://github.com/ifedapoolarewaju/igdm/releases/download/v2.5.1/IGdm_2.5.1_amd64.deb) works for you instead?

See [here](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.5.1) for all release binaries

**Comment by carloshpb** [comment]
Sorry for the delay, the internet is quite slow in here.
Yeah, the [debs](https://github.com/ifedapoolarewaju/igdm/releases/download/v2.5.1/IGdm_2.5.1_amd64.deb) works just fine. 
But even after using it, the AppImage remains with the same error.

**Comment by tewald** [comment]
Same here.
Deb works, AppImage doesn't.
I prefere AppImage, because i'm too lazy to install debs and keep them updated. :-P

**Comment by obliviateandsurrender** [comment]
Same issue on Linux Mint 18.3.
deb works fine though.

**Comment by SimonVanacco** [comment]
This should be fixed with #374 hopefully.
