### ISSUE TITLE
Javascript Json error 

### ISSUE THREAD

**Issue by varwone** [ifedapoolarewaju/igdm#350]
it appears while using it, comes again everytime i write or click around.

![image](https://user-images.githubusercontent.com/8791861/41291990-80dd47c4-6e51-11e8-9f74-8f229c32f376.png)

**Comment by ifedapoolarewaju** [comment]
@varwone but the app keeps working?

**Comment by varwone** [comment]
Yes. Just throws out those messages which makes it unable to use.

Ifedapo .A. Olarewaju <notifications@github.com> schrieb am Do., 14. Juni
2018, 08:30:
