### ISSUE TITLE
App won't start (Atleast not properly)

### ISSUE THREAD

**Issue by VioletasTheThird** [ifedapoolarewaju/igdm#351]
Hey, so I have been using IGdm for a few months now and it was all going very well, however today it automatically updated to a new version and now, after I start igdm, it just runs in the background and no window appears. Are there any logs I can check?

I'm on Ubuntu 18.04

**Comment by octocat8** [comment]
Try starting it from terminal and check for errors. I had a similar experience, here's the fix.
https://github.com/ifedapoolarewaju/igdm/issues/347

**Comment by lokuhra** [comment]
dont start
