### ISSUE TITLE
is it working for anyone as in the appimage point and click ubuntu

### ISSUE THREAD

**Issue by huskymud44** [ifedapoolarewaju/igdm#365]

**Comment by SimonVanacco** [comment]
The Appimage is indeed broken right now. Here is an **easy** workaroud while waiting the .appimage to be fixed:

Go here: [IGdm Github Releases](https://github.com/ifedapoolarewaju/igdm/releases) and download the .zip from the latest release (2.5.1 to this day). Unzip it, launch it, Boom it works.

Reply if you still have issues.
