### ISSUE TITLE
How to solve the problem about "Instagram call checkpoint for this action!" when log in IG:dm?

### ISSUE THREAD

**Issue by Hannah-haha** [ifedapoolarewaju/igdm#366]
How to solve the problem about "Instagram call checkpoint for this action!" when log in IG:dm?
![problems1](https://user-images.githubusercontent.com/40383822/41585914-f70493b2-73dd-11e8-9cd1-a2c7445d9a63.png)

**Comment by yusuf9876543210** [comment]
THIS IS THE PROBLEMS IN THE PLEASE PLEASE KNOW THAT I HAVE A HELP TO TURKEY BEN

**Comment by yusuf9876543210** [comment]
BANADA BÖYLE SORUNLAR OLUYOR LÜTFEN BİLEN BİRİ YARDIM ETSİN BİZE TÜRKÜM BEN
