### ISSUE TITLE
Linux 2.51 electron build error (bug)

### ISSUE THREAD

**Issue by alfieoriginal** [ifedapoolarewaju/igdm#367]
Have this in last upgrade

`module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-2nKGcw2/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
`

Maybe related to [https://github.com/electron-userland/electron-builder/issues/2958](https://github.com/electron-userland/electron-builder/issues/2958)

**Comment by ifedapoolarewaju** [comment]
this seems to be the case indeed. Thank you for the hint

**Comment by Prathik-Jain** [comment]
See #369
