### ISSUE TITLE
After Search, no Messages

### ISSUE THREAD

**Issue by user-4711** [ifedapoolarewaju/igdm#368]
When i start a search in the Input box, and choose one of my results. It is normal to clear the box and type in a new Name, or clear it to see my written Messages. If i choose one then, it doesn´t open on the right side.

Pls help everytime i must Close the Window, reopen it and looged in again. It is so annoying.

**Comment by ifedapoolarewaju** [comment]
> If i choose one then, it doesn´t open on the right side.

what doesn't open on the right side?

**Comment by user-4711** [comment]
The choosed Chat i clicked on. F.E. I search for a Name Testuser1. I click on the Name and write a Message.
Left Side = Searchresults | Right Side = Chat with Testuser 1
Next step i clean the searchbar. Click on a Chat i started before.
Left Side= Old Chats | Right Side Chat with Testuser 1

Now i can click on every Chat or searchresults. The Chat with Testuser 1 stand on the right Side.
