### ISSUE TITLE
APPCRASH

### ISSUE THREAD

**Issue by killertuxX** [ifedapoolarewaju/igdm#37]
Hi! Yes but i fixed it now! :) I don't know what was the problem but i tried installing it like five times and now it works! (sorry for any English mistake)

**Comment by ifedapoolarewaju** [comment]
HI @killertuxX , thank you for reporting this. Was this during installation?

**Comment by ikkamouse** [comment]
Hi ifedapoolarewaju, Have same problem on win 7 SP1 x64.

installation crashes,

Faulting application name: IGdm-Setup-2.2.0.exe, version: 2.2.0.0, time stamp: 0x597fcc70
Faulting module name: ntdll.dll, version: 6.1.7601.23864, time stamp: 0x595fa490
Exception code: 0xc0000005
Fault offset: 0x000346f3
Faulting process id: 0xb28
Faulting application start time: 0x01d357fe7ce1e668
Faulting application path: C:\Users\XXXXXX\Downloads\IGdm-Setup-2.2.0.exe
Faulting module path: C:\Windows\SysWOW64\ntdll.dll
Report Id: bb4a7dfe-c3f1-11e7-b57c-00248c4a45eb

**Comment by ifedapoolarewaju** [comment]
@ikkamouse is it the same with you? Were you later able to install it? Or does it fail continuously?

**Comment by ikkamouse** [comment]
I cannot manage to get it installed.

**Comment by ikkamouse** [comment]
Hi ifedapoolarewaju,
you have any clue what the cuase can be ?  And how to make it install ?

Thankz

**Comment by killertuxX** [comment]
Try to download again.That's what i did. (Maybe it was some kind of file corruption in my case)

**Comment by ifedapoolarewaju** [comment]
@ikkamouse unfortunately, this is something I'd have to investigate before getting a better either of it's origin. This is most likely an issue with the installer and not the app itself.

Could you try what @ikkamouse, suggests? He's the one who initially reported this, and since he got it to work that way, then it might be worth the shot 🙂 

In the future, it would be better for me to sign the installers, so the downloads can be verified for corrupt data.

thank you for the hint @killertuxX

**Comment by ikkamouse** [comment]
@ killertutuxX : thankz, tried that but no luck , same error.

Gonna try some other things. if I find the cause or a solution  I will post it here for sure.
Cheers.

**Comment by Z-13** [comment]
I have same problem!
_Win 7 SP1 x64_ 
**Installer: IGdm-Setup-2.2.0.exe**

`Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IGdm-Setup-2.2.0.exe
  Application Version:	2.2.0.0
  Application Timestamp:	597fcc70
  Fault Module Name:	StackHash_c4de
  Fault Module Version:	6.1.7600.16385
  Fault Module Timestamp:	4a5bd98a
  Exception Code:	c0000374
  Exception Offset:	00008518
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1049
  Additional Information 1:	c4de
  Additional Information 2:	c4de24457f845e61bc6fba9bcbe68b26
  Additional Information 3:	d543
  Additional Information 4:	d54360b77d1757f8398f5870b2fe6ca4`

Compatibility mode on Windows 7 get starting install BUT to repeat APPCRASH

Help me fix it!
Thx!

**Comment by Z-13** [comment]
Installer v2.1.0 is installed (https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.1.0)
