### ISSUE TITLE
I can't install IG:dm on UBUNTU 18.04 LTS 

### ISSUE THREAD

**Issue by Salvo107** [ifedapoolarewaju/igdm#371]
On Ubuntu 18.04, I can't install the file .appImmage of IG:dm, I saw the old issue about the installation, but I can't understand how I can install it...

**Comment by SimonVanacco** [comment]
Here is a workaroud while waiting the .appimage to be fixed:

Go here: [IGdm Github Releases](https://github.com/ifedapoolarewaju/igdm/releases) and download the .zip from the latest release (2.5.1 to this day). Unzip it, launch it, Boom it works.

Reply if you still have issues.

**Comment by SimonVanacco** [comment]
#374

**Comment by krstefski** [comment]
When i unzip it, how exactly should i launch it(what file)?
