### ISSUE TITLE
<unsupported message format>

### ISSUE THREAD

**Issue by wryrenee** [ifedapoolarewaju/igdm#377]
Whenever others send a photo, reply to story, or video, all I receive is the message "<unsupported message format>". Does anyone know what is wrong or how to solve this problem? Thanks.

**Comment by SimonVanacco** [comment]
This software is not yet supporting some media types. 
This is on the todo-list but we are lacking time at the moment. 

Thanks for your support
Simon

**Comment by aninnha** [comment]
This software is not yet supporting some media types.
I hope you can fix it the soon as you can!

**Comment by lcanpoli** [comment]
hi, this issue is still prevalent. solution coming soon?
