### ISSUE TITLE
It only supports Windows emojis.

### ISSUE THREAD

**Issue by Xadyxx** [ifedapoolarewaju/igdm#378]
Hello, it would be REALLY useful to be able to choose between android/windows/iOS emojis... Or at least just android.

 Thank you very much I would be really happy if you added this feature.

**Comment by SimonVanacco** [comment]
Hi!

I am looking on updating the emojis support for igdm for a while. I'll keep experimenting by myself, maybe another contributor will also look into it. 

Thank you for your support and your great ideas,

Simon

**Comment by m-sameer** [comment]
You should use just one emoji font for every platform. Use [EmojiOne](https://www.emojione.com/).
