### ISSUE TITLE
Post an URL but it won't link.

### ISSUE THREAD

**Issue by gillang3** [ifedapoolarewaju/igdm#379]
Did post a link but you click on it and nothing happen.  http://ibb.co/mMZs6d

**Comment by kali2585** [comment]
I had the same thing happen. They had to copy/paste straight into their browser. I can't even copy/paste. I have to type it into the browser.

**Comment by brasofilo** [comment]
Same happening here. Running IG:dm 2.6.1 on OS X 10.11.6
