### ISSUE TITLE
copycat scammer ?

### ISSUE THREAD

**Issue by alibekch** [ifedapoolarewaju/igdm#38]
http://i-directmessage.com uses project assets however directs to multiple advertisement sites...

**Comment by ifedapoolarewaju** [comment]
@alibekch wow thank you for reporting this. I'm not sure how to handle this, but I guess the least I could do is put a warning/disclaimer on the README and the website.

**Comment by alibekch** [comment]
@ifedapoolarewaju commercialize asap, start selling your product as soon as it is usable and copycats will perish. 
check on plugn.io for a great example of DM+comment management on IG.
