### ISSUE TITLE
I can't see images.

### ISSUE THREAD

**Issue by AnneShirou** [ifedapoolarewaju/igdm#387]
![tuturu](https://user-images.githubusercontent.com/40903293/42404013-9ae6ccd4-8153-11e8-89d7-fe7ab227afa2.jpg)

When my friends send me images, I get the error <unsupported message format>, and I can not see the images. Also, when I send images, I can only send in .jpg format, and some of them are not sent. Please, correct that error. Thank you.

**Comment by drum-6** [comment]
whenever someone sends me an image it says "<unsupported message format>' if this continues I will consider deleting the app 
![image](https://user-images.githubusercontent.com/46039841/50323739-2a223f00-052f-11e9-8e83-cc299b75cc48.png)

**Comment by SantiChaillou** [comment]
same over here
