### ISSUE TITLE
init.js Error !

### ISSUE THREAD

**Issue by abdiprawira** [ifedapoolarewaju/igdm#398]
**module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_DM.App5d3BrX/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3**

cant run this app image, my OS is Parrot OS debian based/Linux

**Comment by jonnyeom** [comment]
Others applications seem to have this issue as well > https://github.com/electron-userland/electron-builder/issues/2958.

They just rolled back the electron-builder version to v20.14.7.

**Comment by italo-rp** [comment]
I'm getting he same error.

**Comment by kodarfour** [comment]
I'm gettting the same error. I've noticed that people have said that they just downgraded to electron-builder@20.14.7 but I do not how to go about that. If anybody knows how, can they please assist me.

**Comment by abdiprawira** [comment]
SOLVED !! dont Downloads the AppImage file, download IGDM as Deb file, and install that, this work for me
