### ISSUE TITLE
i cant see pictures on my windows 7

### ISSUE THREAD

**Issue by lorealallen** [ifedapoolarewaju/igdm#40]
it wont show picture

**Comment by ifedapoolarewaju** [comment]
Thank you for reporting! Do you mind explaining more the problem you are facing? 🙂

Share a screenshot maybe?

**Comment by lorealallen** [comment]
im on my windows 7 and when i want to see the picture it says unsupported
message format i have the instagram dm thing
can you please fix this

**Comment by ifedapoolarewaju** [comment]
> unsupported message format

It's probably an IG story that someone sent? If it's an image or an IG post then you should be able to view it. IG Stories are currently not implemented yet.

Can you confirm what kind of message was sent to you? Was it a story? Or a post? Or a directly uploaded image?
