### ISSUE TITLE
I cant connect my instagram account

### ISSUE THREAD

**Issue by jackiboiii** [ifedapoolarewaju/igdm#400]
when I try to login to my instagram account it says instagram call checkpoint for this action and it asks me on my instagram to verify if I was trying to connect, I press= YES, nothing happens.

**Comment by yusuf9876543210** [comment]
PLEASE PLEASE PLEASE PLEASE HELP US TO KNOW THIS PROBLEM

**Comment by yusuf9876543210** [comment]
Instagram call checkpoint for this action! hatası bende alıyorum bilen yazsın ben TÜRKÜM
