### ISSUE TITLE
no message

### ISSUE THREAD

**Issue by dhosheena** [ifedapoolarewaju/igdm#401]
i am not able to have my messages

**Comment by toxi22** [comment]
I can not see the list of interlocutors and accordingly I do not see the message. The list of interlocutors is empty.

**Comment by fkinnar** [comment]
Same issue with the Linux version (2.6.0). 

The contact list stay empty, I can't see any message. But I can search for a contact and send him en new message (but afterward, I do not see the message in the list)

The Windows version works properly...
