### ISSUE TITLE
Change the igdm.me website to HTTPS

### ISSUE THREAD

**Issue by riahc3** [ifedapoolarewaju/igdm#403]
You really need to change the site to HTTPS.

Nowadays Let's Encrypt provides a free cert. That is no reason not to change it (and the entire igdm backend infrastructure if any) to use HTTPS.

**Comment by ifedapoolarewaju** [comment]
@riahc3 this hasn't been a priority because the website is merely a static page that does not transmit user data to the other end. It is only available so you can download the IG:dm app itself. And the download links themselves are in `https`.
