### ISSUE TITLE
auto login - how and where is my password saved - please help!

### ISSUE THREAD

**Issue by dough82** [ifedapoolarewaju/igdm#404]
even when i log out and click log in again the login is automatic, where is my passwords saved? how is it saved? i've checked my saved passwords in keyring, chrome and safari but it isn't there... please help (sorry if this question is stupid)

**Comment by ifedapoolarewaju** [comment]
> even when i log out

How exactly do you log out?

**Comment by dough82** [comment]
on my profile picture i choose "log out", when i log in again i'm not asked for my password, it seems to be stored automatically, but where?

**Comment by ifedapoolarewaju** [comment]
this should not happen. Your password is not saved anywhere, only the session is saved. And whenever you logout the session should be deleted so I am surprised you are experiencing this.

What version of IGdm are you using? And where did you download it from?
