### ISSUE TITLE
Connect through PROXY

### ISSUE THREAD

**Issue by baptistegh** [ifedapoolarewaju/igdm#408]
Hey,

I've tried to connect my account on windows.
Error : tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3131 3131:80

A proxy is configured on my system (Windows 10)

![image](https://user-images.githubusercontent.com/22121816/42891739-5f080424-8ab0-11e8-9ed5-c0a8fb3b6615.png)

 Can you help me ?

Thx !

**Comment by AhHa45** [comment]
I get a timeout, need to set proxy settings!

**Comment by briancblog** [comment]
Please deploy a proxy configuration! Thanks!
