### ISSUE TITLE
Delete a conversation

### ISSUE THREAD

**Issue by shiverburngalaxy** [ifedapoolarewaju/igdm#41]
why does it make a new group chat when i just messaged in one and do i delete a conversation

**Comment by ifedapoolarewaju** [comment]
> why does it make a new group chat when i just messaged in one

Yes, this is a known issue and would be fixed pretty soon (most likely this coming weekend 🙂 )

> do i delete a conversation

Unfortunately the feature to delete a conversion has not been implemented yet, but I do agree it is a very useful feature, and is worth looking into.

**Comment by baptx** [comment]
@ifedapoolarewaju there should be an option to delete both an entire conversation and a single message. This is an important feature, especially for people that are not using the official mobile app.

**Comment by baptx** [comment]
@ifedapoolarewaju why did you close all the issues? It looks like the problem is not fixed.

**Comment by ifedapoolarewaju** [comment]
It’s a duplicate, please search other open issues to see another similar existing issue

**Comment by baptx** [comment]
@ifedapoolarewaju ok, I found the same issue here: https://github.com/ifedapoolarewaju/igdm/issues/506 but it was created in August 2018 which is then a duplicate of this one created in November 2017. It would have been better to keep the original one and close the duplicates. Or there was another issue created before that I did not see?

**Comment by ifedapoolarewaju** [comment]
@baptx perhaps, but what really mattered to me at the time was keeping only 1 version of the issue.
