### ISSUE TITLE
IGDM not working..

### ISSUE THREAD

**Issue by Lil-Wrench** [ifedapoolarewaju/igdm#413]
This is my first time downloading igdm. When I launch the application I just get a white screen with some dropdown menus, "Edit, View, Window, Help" I tried uninstalling and reinstalling but nothing seems to help. Please release a patch fixing this issue.

**Comment by trcpicuals** [comment]
This is my first time downloading igdm. When I launch the application I just get a white screen with some dropdown menus, "Edit, View, Window, Help" I tried uninstalling and reinstalling but nothing seems to help. Please release a patch fixing this issue.
