### ISSUE TITLE
"IG.DM"

### ISSUE THREAD

**Issue by lovelyjoxxy** [ifedapoolarewaju/igdm#417]
a group chat I'm in isn't allowing me to access the newer messages or content of the chat nor will it let me text in said chat. whenever i try to  (i even tried uninstalling and re-installing ) it sends the message to another person in my dms. same with other people in my dms. please fix this bug and or make a newer version with more features. id say 3.5/4.0 but overall great app!

**Comment by alinamazov01** [comment]
mesaj silme
