### ISSUE TITLE
Not opening on my windows

### ISSUE THREAD

**Issue by chinnatron** [ifedapoolarewaju/igdm#42]
When i run the igdm setup, it asks me if i want to run it and i click "run". then nothing happens after that.

**Comment by ifedapoolarewaju** [comment]
This is a weird behavior, could you try downloading the setup again from the website again and restarting your system before trying a fresh installation?

**Comment by salvatorefoderaro** [comment]
Same problem here. Last Windows 10 CU. If I try to run it in "Compatibility mode" I can get the installer windows but after that crashes. Just tried redownload and system's restart

**Comment by ifedapoolarewaju** [comment]
closing this as a duplicate of https://github.com/ifedapoolarewaju/igdm/issues/52
