### ISSUE TITLE
Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443

### ISSUE THREAD

**Issue by jakesterjung** [ifedapoolarewaju/igdm#425]
Trying to log in IGdm on windows 7 desktop, and failed, shows this "Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443"
Please help, thanks!

**Comment by wendyswaim** [comment]
Same as me, just don't know what is going wrong. Need help too.
