### ISSUE TITLE
v. 2.5.x AppImage does not start on Linux

### ISSUE THREAD

**Issue by anhel-strauke** [ifedapoolarewaju/igdm#427]
IGdm **2.5.1** crashes with error messages in the terminal immediately after launch. Same for **2.5.0**. Message is:

```
anhel@ghost:~/Applications$ ./IGdm-2.5.1-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm-21QYWqp/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```
Version **2.4.0** launches normally, but it's unusable because it downloads updated version and removes itself.

OS: elementary 0.4.1 Loki (based on Ubuntu 16.04)

**Comment by lenowng** [comment]
+1

**Comment by atnimak** [comment]
+1 
I used .deb package to avoid this problem, but this is certainly not the solution.
