### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by rudyskusuma** [ifedapoolarewaju/igdm#428]
Instagram call checkpoint for this action! 
how to fix this

**Comment by atnimak** [comment]
+1
I have the same problem

**Comment by Mspears20** [comment]
+2
I have the same problem
Plz help

**Comment by uchari** [comment]
+3
I have also the same problem... When I try to authorize the app it looks like Instagram doesn't allow it.
Please if anyone that have this problem could solve it.

**Comment by zyanlin** [comment]
+4
I have the same problem..

**Comment by nikkib246** [comment]
I disable the account for about three hours and i still couldn't sign in.
