### ISSUE TITLE
IG DM NOT WORKING

### ISSUE THREAD

**Issue by itszainebxo** [ifedapoolarewaju/igdm#434]
the ig dm download is no longer working i have uninstalled it and installed it 3 times and it still doesnt work when i try to log in it says please try again in a couple of minutes i restarted my laptop and it still wouldnt let me log on for the past hour

**Comment by mateusz-domagalski** [comment]
@itszainebxo 
Same, I'm getting this error message:
<img width="374" alt="screen shot 2018-07-30 at 08 45 00" src="https://user-images.githubusercontent.com/26458269/43381422-e498a8dc-93d4-11e8-9c4b-d1952040bbb4.png">
