### ISSUE TITLE
Window Resize On Resize Not Working

### ISSUE THREAD

**Issue by sibaar** [ifedapoolarewaju/igdm#45]
Using Ubuntu 17.10
IGDM 2.2.

Cannot resize window. It's far too large. It does not fit on my screen. Resize is locked. 
https://imgur.com/a/9jIOu
^screenshot^

Discovering this project of yours made me very happy. Props to you, mate.

**Comment by ifedapoolarewaju** [comment]
@sibaar limiting the the minimum screensize was deliberate, because the UI would get easily ugly at very tiny screen width. What did you have in mind? How small do you wish the screen size could be reduced?

**Comment by sibaar** [comment]
Vertically, the window doesn't even fit on my screen. That is my primary concern.

**Comment by ifedapoolarewaju** [comment]
@sibaar I have fixed this, and it will be released with the next version

**Comment by ifedapoolarewaju** [comment]
fixed here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.4.0
