### ISSUE TITLE
instagram call  checkpoint for this action

### ISSUE THREAD

**Issue by XeroLucifer** [ifedapoolarewaju/igdm#466]
i can't log in , please fix it quickly i need ign dm

**Comment by juliomaister** [comment]
Same here

**Comment by sanjayatony** [comment]
yes same here

**Comment by XeroLucifer** [comment]
today is still no working

**Comment by felicaminos** [comment]
Que tengo que hacer para poder entrar si tengo este problema?

**Comment by XeroLucifer** [comment]
i don't know the developer has to fix

**Comment by hiryu85** [comment]
Thanks for Fix ;-) @ifedapoolarewaju
