### ISSUE TITLE
Multiple accounts in IGDM

### ISSUE THREAD

**Issue by toxi22** [ifedapoolarewaju/igdm#474]
I would like to be able to use several accounts in IGDM and switch between them in order not to leave the existing profile or install / run two copies of the application with different profiles.

**Comment by ifedapoolarewaju** [comment]
While this feature is not currently available on IGdm, please check out [IGdm Pro](https://pro.igdm.me) which has support for this feature and a few others

**Comment by ifedapoolarewaju** [comment]
closing as duplicate
