### ISSUE TITLE
Instagram call checkpoint for this action! Cant connect

### ISSUE THREAD

**Issue by Neroid** [ifedapoolarewaju/igdm#475]
As the title says i apply my credidentials and i get the Instagram call checkpoint for this action!
I dont have two step factor set up so it worries me on how i would be able to connect.

**Comment by shave7777** [comment]
same problem and there is more

**Comment by laraschmidtfotografia** [comment]
Same problem here....

**Comment by Abadin420** [comment]
Yup... :/

**Comment by Abadin420** [comment]
same... :sob:
