### ISSUE TITLE
instagram call checkpoint required

### ISSUE THREAD

**Issue by brookelynnbarry** [ifedapoolarewaju/igdm#483]
what is an " instagram call checkpoint " ?????????

**Comment by Abadin420** [comment]
Its for me too, just said "Instagram call checkpoint for this action!" :sob: :sob:

**Comment by brookelynnbarry** [comment]
temparaily disable your account, wait 2-3 hours then try again.
DONT sign in before doing that.

**Comment by barbaraandrews** [comment]
And how you temporarily disable your account? i don't know how to do that

**Comment by brookelynnbarry** [comment]
go on your profile. Click “edit profile”. Scroll down and click “temporarily disable account”.select “just need a break”.

Sent from Mail for Windows 10
