### ISSUE TITLE
IG:dm | cannot login

### ISSUE THREAD

**Issue by essadebora** [ifedapoolarewaju/igdm#492]
hi! I can not log in to the GI: dm. my account does not have two verification steps and even informing in the instagram application that the access is mine, it continues giving error. can you help me? thanx!

![image](https://user-images.githubusercontent.com/42307807/43997752-145bd9d2-9dbb-11e8-87bb-8d9243a918fb.png)

**Comment by joshuaaaaaa** [comment]
happens to me as well
