### ISSUE TITLE
IG:dm

### ISSUE THREAD

**Issue by andyhuertam** [ifedapoolarewaju/igdm#496]
I have a problem with the app, it doesnt permit me to log in, I write my username and password and then a menssage says: Instagram call checkpoint for this action!; then I open instagram and confirm that is me, but  nothing hapen, I still cant open IG:dm

**Comment by Shayek** [comment]
I have a problem with this app, it is not letting me to login, it says "Instagram call checkpoint for this action!" Then when it allows me to login it doesnt let me see my messages
