### ISSUE TITLE
Won't let me login

### ISSUE THREAD

**Issue by DailyIntruder** [ifedapoolarewaju/igdm#501]
I've checked if I have messed up my Username and Password but, it's correct.I've tested this by logging into Instagram same Username and Password but, for some reason when I attempt at logging into Instagram from this app I'm unable to log in for some reason. Please help,thank you for reading.

**Comment by alessby** [comment]
> I've checked if I have messed up my Username and Password but, it's correct.I've tested this by logging into Instagram same Username and Password but, for some reason when I attempt at logging into Instagram from this app I'm unable to log in for some reason. Please help,thank you for reading.

me too, what did you do?
