### ISSUE TITLE
error on running the app for a first time.

### ISSUE THREAD

**Issue by Xdabier** [ifedapoolarewaju/igdm#502]
### after running the chmode a+x in the file I tried the ./ command and it came out like this .

~$ ./IGdm-2.5.1-x86_64.AppImage 
module.js:545
    throw err;
    ^
===============================================================================

Error: Cannot find module '/tmp/.mount_IGdm-2srSmG1/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
===============================================================================

**Comment by sutriman1995** [comment]
I have the same problem

**Comment by murphinator** [comment]
Ditto

**Comment by sutriman1995** [comment]
I've been fixed this problem, with Xdabier's way using npm. But, I've new problem when login, its called "Instagram call checkpoint for this action!"

**Comment by Xdabier** [comment]
@sutriman1995 do you have second factor authentification in your account ?

**Comment by Akhelez** [comment]
Hi Xdabier, Can u tell me please how do i do to run the source with npm ??
i had xubuntu ,32 bits, and it gives me the same error :((

**Comment by Xdabier** [comment]
@Akhelez all you need to dois to follow the steps in [here!](https://github.com/ifedapoolarewaju/igdm#local-development)

**Comment by Akhelez** [comment]
dude im dumb as f****... :(((
cant, and im really trying to install node and didnt get it... :'(
To setup this project locally for development purposes please follow the following steps:

Ensure you Node.js installed. See

Clone this repo by running the command - git clone https://github.com/ifedapoolarewaju/igdm.git

Navigate to the directory where the repo is cloned to. (e.g cd igdm)

Run npm install to install all the dependencies.

Start the application locally by running npm start

That's it! :) Now you can have those pull requests rolling in! :D


its driving me crazy :'(((
