### ISSUE TITLE
module.js:545 throw err

### ISSUE THREAD

**Issue by dachronos** [ifedapoolarewaju/igdm#511]
Debian 8.10 Jessie
If start normally nothing happnes, but at run in terminal get this error.

Error: Cannot find module '/tmp/.mount_igdm.Az7l25R/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
dachronos@ZX4250:/opt$

**Comment by Batcastle** [comment]
I'm running Ubuntu 18.04.1 and I'm getting a similar error.

Print out from running in terminal:
```
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_IGdm.AFH1aQd/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

**Comment by kimpastro** [comment]
Same here.

**Comment by Batcastle** [comment]
I found that if you uninstall all of OpenArena and it's dependencies (except for libc6) and get the game from the official website it runs just fine. 

Just decompress the zip and go.

**Comment by kimpastro** [comment]
@Batcastle what are you talking about?

**Comment by Batcastle** [comment]
@kimpastro Sorry about that XD. I was working on a bug for another app that was throwing a seg fault too and thought I was on their github posting the fix I had found and by the time I realized what I had done it was too late. Please just ignore that post.

**Comment by kimpastro** [comment]
@Batcastle ok, no problem.
