### ISSUE TITLE
A JavaScript error occurred in the main process - Error: UNKNOWN: unknown error, open 'C:\Users\<userName>\AppData\Roaming\IGdm\session-cookie\<userMail>.json'

### ISSUE THREAD

**Issue by starnutoditopo** [ifedapoolarewaju/igdm#517]
Periodically (I didn't check how frequently, exactly, but about every minute) a popup is displayed with this title:

> A JavaScript error occurred in the main process

reporting the following message:

> Error: UNKNOWN: unknown error, open 'C:\Users\<userName>\AppData\Roaming\IGdm\session-cookie\<userMail>.json'

The specified file DOES exist and contains a (pretty long) json.
The json file contains lot of data, whose structure is this (here content of sub-properties are replaced with dots for brevity):

```
{  
   "instagram.com":{  
      "/":{  
         "ds_user":{  ... },
         "rur":{  ... },
         "csrftoken":{  ... },
         "mid":{  ... },
         "ds_user_id":{  ... },
         "urlgen":{  ... },
         "sessionid":{  ... },
         "mcd":{  ... },
         "is_starred_enabled":{  ... },
         "shbid":{  ... },
         "shbts":{  ... }
      }
   },
   "i.instagram.com":{  
      "/":{  
         "csrftoken":{  ... }
      }
   }
}

```

**Comment by snowwyplayzz** [comment]
happens to me to

**Comment by ifedapoolarewaju** [comment]
what version of IGdm are you using? could you try to logout and login again?

**Comment by Jarokgamer** [comment]
I have the same problem, how do I solve this?
