### ISSUE TITLE
Doesn't Run on windows 7 and 10 

### ISSUE THREAD

**Issue by uzorjchibuzor** [ifedapoolarewaju/igdm#52]
I tried to run this program on Windows 7, no dice.

What was I doing wrong?

**Comment by kinduff** [comment]
Same case with Windows 10

**Comment by manguszta** [comment]
Can't run on Win 7, 64-bit, crashes at start.

**Comment by ifedapoolarewaju** [comment]
@manguszta does it install for your case? Or does it crash when you try to install it?

**Comment by uzorjchibuzor** [comment]
@ifedapoolarewaju It dosent install, crashes when I try to install it.

**Comment by ifedapoolarewaju** [comment]
@uzorjchibuzor can you install the latest version and see if the issue persists? I made some changes in the way the installers are packaged, and it **might** have fixed the issue.

**Comment by uzorjchibuzor** [comment]
@ifedapoolarewaju okay, send me the link

**Comment by ifedapoolarewaju** [comment]
https://github.com/ifedapoolarewaju/igdm/releases/download/v2.3.1/IGdm-Setup-2.3.1.exe

**Comment by manguszta** [comment]
@ifedapoolarewaju it crashes before installing. I could only download it for the 50th time (AT LEAST). Probably a corrupted download.

**Comment by uzorjchibuzor** [comment]
@ifedapoolarewaju is it the same as the one on igdm.me? I am currentlyu downloading that one and its 2.3.1 too

**Comment by ifedapoolarewaju** [comment]
@uzorjchibuzor it's the same, yes

**Comment by uzorjchibuzor** [comment]
@ifedapoolarewaju no dice, see attachment 
![gitt](https://user-images.githubusercontent.com/32690770/34719549-3aae7dc0-f509-11e7-811e-999ea1e97007.JPG)

**Comment by uzorjchibuzor** [comment]
That is the banner I get when I try to open the installer

**Comment by manguszta** [comment]
Why does the download stops 49 out of 50 times?

**Comment by ifedapoolarewaju** [comment]
> Why does the download stops 49 out of 50 times?

**Comment by uzorjchibuzor** [comment]
@manguszta my download runs through no issues downloading the .exe file, the setup doesn't run though

**Comment by ifedapoolarewaju** [comment]
> Why does the download stops 49 out of 50 times?

this is a first for me. Perhaps internet/network issues?

**Comment by manguszta** [comment]
I try to download from home. The one that downloaded, crashed before installing.

**Comment by manguszta** [comment]
I managed to download from home, but it still crashes before installing.

**Comment by uzorjchibuzor** [comment]
I formatted my Windows system and installed Linux and I have to say that the Linux Igdm software works like a charm. Thanks guys.
