### ISSUE TITLE
Iogin

### ISSUE THREAD

**Issue by jvvy-c137** [ifedapoolarewaju/igdm#520]
I cant login because it sends a location verification and when i press yes to enter it still does nothing. Whats going on?

**Comment by a-vasyliev** [comment]
I have similar problem: http://prntscr.com/kmjt5x

**Comment by JanZornicka** [comment]
same thing

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*
