### ISSUE TITLE
Doesn't allow me to login to Instagram

### ISSUE THREAD

**Issue by Rogelio2** [ifedapoolarewaju/igdm#521]
![2018-08-24 17_15_28-ig_dm - instagram desktop messenger](https://user-images.githubusercontent.com/4323367/44612891-60d68b80-a7c1-11e8-9d63-7714c4d00c41.png)

**Comment by maheen09** [comment]
Doesn't allow me to login to Instagram

**Comment by ifedapoolarewaju** [comment]
Please update your app to the latest version on http://igdm.me
