### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by redkim360** [ifedapoolarewaju/igdm#525]
Am using this medium to report my inability to login my Instagram account with igdm

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*

**Comment by ifedapoolarewaju** [comment]
Please update your app to the latest version on http://igdm.me
