### ISSUE TITLE
instagram check point

### ISSUE THREAD

**Issue by wailbr4** [ifedapoolarewaju/igdm#526]
everytime i confirme instagram check point it says try again till i get blocked

**Comment by sublingualwart** [comment]
same here

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*

**Comment by ifedapoolarewaju** [comment]
Please update your app to the latest version on http://igdm.me
