### ISSUE TITLE
id:dm

### ISSUE THREAD

**Issue by ayshasgarzade** [ifedapoolarewaju/igdm#528]
Instagram call checkpoint for this action!
what this mean? what must i do?

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*
