### ISSUE TITLE
texts aren't visible

### ISSUE THREAD

**Issue by dedeeedd** [ifedapoolarewaju/igdm#53]
i cant see any of my texts unless i send someone something so i cant know if someone messaged me unless i send them a text and it becomes visible ,so it'd be nice to know how i could fix that if its somehow my mistake or if u could fix that because they haven't been showing up for about a week or so.
thxx xx

**Comment by ifedapoolarewaju** [comment]
@dedeeedd thank you for reporting. Yes this is a known issue, for now restarting the application should solve the problem

**Comment by dedeeedd** [comment]
ive tried that a couple of times but still only 4 messages are showing up :c
