### ISSUE TITLE
issue about IGDM

### ISSUE THREAD

**Issue by priyaselv** [ifedapoolarewaju/igdm#535]
Hi. I tried install the app and i have successfully installed it but i cannot login my account. can i know why ?

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*

**Comment by ifedapoolarewaju** [comment]
What happens when you try to login?
