### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kimiasmith** [ifedapoolarewaju/igdm#537]
hi i recently have a problem and when i wanna log in to my acc it says instagram call check point for this action and i cannot access my acc what should i do?

**Comment by EyesReye** [comment]
Edit Profile
Disable Account
Just want a break
Enter password
Confirm

Wait 2 hours
Login into Instagram using the IG:DM Application (important).

*DO NOT LOGIN FOR THE FIRST TIME ON YOUR PHONE / WEB BROWSER*

**Comment by kimiasmith** [comment]
hi thx but still have this problem

**Comment by ifedapoolarewaju** [comment]
Please update your app to the latest version on http://igdm.me
