### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by NeNeNeNe18** [ifedapoolarewaju/igdm#54]
i type my correct user and passcode and wont work

**Comment by ifedapoolarewaju** [comment]
@NeNeNeNe18 thank you for reporting this.

does it show an error message? 
do you have two-factor authentication enabled?
what OS are you running it from?

**Comment by Kovah** [comment]
@ifedapoolarewaju 
i have the same problem. 2FA is activated.
I enter my credentials, click login, nothing happens. But i do get the passcode via phone. Seems IG DM does not support 2FA-enabled accounts?

**Comment by jillianb1** [comment]
every time i try to login it says instagram has called a checkpoint! then my instagram says suspicious login attempt and everything is messed up.

**Comment by nurps** [comment]
Same here "Instagram call checkpoint for this aciont!"
