### ISSUE TITLE
i cant open it

### ISSUE THREAD

**Issue by ShadowJess** [ifedapoolarewaju/igdm#541]
when i try to log in it says: Instagram call checkpoint for this action
and i cant use the desktop messenger please help
![ss hata](https://user-images.githubusercontent.com/42798839/44773048-33e6f780-ab78-11e8-88f3-0b97e193a11b.JPG)

**Comment by EyesReye** [comment]
Edit Profile -> Disable Account (Just want a break) -> Confirm by entering your password -> Wait 2 hours, Login into Instagram using the IG:DM Application (Do not login for the first time on your phone/browser).

**Comment by billysio** [comment]
i have the same problem need heeeeeeeeeeeeelp plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by yambadr** [comment]
@EyesReye it worked! thank you!
