### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by bethhhyyyy** [ifedapoolarewaju/igdm#546]
I enter my account credentials and it doesn't log me in. An error message pops up saying "Instagram call checkpoint for this action!" What do I do? I have attached a screengrab of the message. 
![image](https://user-images.githubusercontent.com/42849848/44877995-f27f4680-ac62-11e8-9898-99a46aa3886b.png)

**Comment by rewantjain** [comment]
I am having the same issue.
