### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by DMD003** [ifedapoolarewaju/igdm#55]
Every time i put my Instagram information in i wait about a minute and the it gives me a error code like this

Error: connect ETIMEDOUT 157.240.2.52:443

I don't know what i'm doing wrong can you help

**Comment by ifedapoolarewaju** [comment]
@DMD003 since this is a timeout issue, can you confirm this has not to do with just the internet connection of the device from which you run the app?

**Comment by DMD003** [comment]
it shouldn't be the connection because I have disconnected and then reconnected to my device to the internet.

**Comment by DMD003** [comment]
but now its giving me a different error code

Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443
