### ISSUE TITLE
Can't login to app

### ISSUE THREAD

**Issue by happEsextalk** [ifedapoolarewaju/igdm#558]
I just downloaded this app for my Mac, and when I try to login with my IG credentials, i'm getting the following message: "Instagram call checkpoint for this action!" - Not really sure what that means?

**Comment by th8tawavez** [comment]
the same thing happened to me is there anything I can do differently on my end?  I'm pretty sure its Instagrams authentication process.

**Comment by desperateforattention** [comment]
Same thing happened to me as well. No matter how many times I authorize my login on Instagram the IG:dm app still gives me that warning. idk wut that's all about
