### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by likhith823** [ifedapoolarewaju/igdm#563]
When I enter the correct username and password required for logging into IG:dm. I got an error when clicked on login as 'Instagram call checkpoint for this action!'. How do I resolve this?

**Comment by ulissesdore** [comment]
nem sei mano

**Comment by damarenc21** [comment]
its keeps saying ig calls checkpoint can some one help me

**Comment by opalbaloch** [comment]
When I enter the correct username and password required for logging into IG:dm. I got an error when clicked on login as 'Instagram call checkpoint for this action!'. How do I resolve this?

**Comment by opalbaloch** [comment]
Queqe answer pleas
