### ISSUE TITLE
"Not possible to parse API response" Error

### ISSUE THREAD

**Issue by shiftbutton** [ifedapoolarewaju/igdm#567]
First, i couldn't sign in. So I searched about and I found a "solution" https://github.com/ifedapoolarewaju/igdm/issues/60 Then I tried it and now I can even sign in any of my accounts in any of my devices. (Both PC and phone). How can I fix this?

http://prntscr.com/kq8c2s The solution that I tried

http://prntscr.com/kq8bx6 Current error

**Comment by janak6625** [comment]
this solution is not working, you want us to disable our accounts?  what a nonsense solution.

**Comment by janak6625** [comment]
any logical solution available?  i try disabling my account and try to login with igdm still not working
