### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by bernzrdo** [ifedapoolarewaju/igdm#57]
I want to install this program but it just saying "verifying installer" and then closes and doesn't install

**Comment by robnu** [comment]
are you on windows? same thing was happening to me last night. i restarted the computer but nothing still.
i gave up and when i tried again this morning after turning off the computer it worked just fine. windows is such a pos lmao

**Comment by threenator** [comment]
Delete all igdm data from %appdata% and try again

**Comment by ifedapoolarewaju** [comment]
> I want to install this program but it just saying "verifying installer" and then closes and doesn't install

Do you have internet connection when you try to install it?

Usually the "Installation verification" requires internet connection, and when there isn't any, it simply disappears
