### ISSUE TITLE
igdm

### ISSUE THREAD

**Issue by szl123456789** [ifedapoolarewaju/igdm#577]
is wont open correctly and whenever i type something in it rejects it

**Comment by solomonovo** [comment]
Whenever I type in my log in it won't work it says "No configs given"

**Comment by szl123456789** [comment]
what

**Comment by szl123456789** [comment]
Hi,

I just entered the Quizlet Live Fall Giveaway for a chance to win $1,000
for my classroom!

To enter: Play Quizlet Live with your classes as much as you can by Friday,
November 1st. Each completed game counts as one entry — so the more games
you play, the better your odds!

I thought you might want to enter too. And if you refer others, you get
more chances to win. :)

http://bit.ly/2N4t4os

**Comment by szl123456789** [comment]
Thanks, I'll check it out! Oh wait, IT'S TOO LATEEEE... WHY CAn't I ever
check my emaillll
