### ISSUE TITLE
i couldn't log in IG:dm

### ISSUE THREAD

**Issue by lisaqianguo** [ifedapoolarewaju/igdm#585]
I couldn't log in the ig:dm app. after install, when i opened it, it showed  Error: connect ETIMEDOUT 59.24.3.173:443. what does this mean? how can i fix this?
![qq 20180911105315](https://user-images.githubusercontent.com/43160236/45335341-7ca7a300-b5b1-11e8-908f-f2004c6d2619.jpg)

**Comment by April2005** [comment]
I met this problem too.
How to solve it?
