### ISSUE TITLE
Not actually an issue!

### ISSUE THREAD

**Issue by gondimjoaom** [ifedapoolarewaju/igdm#59]
Hey guys! Love your project. Thanks by the way.

I would like not to have to login again everytime I close the program. And I think that's it by now :)

**Comment by ifedapoolarewaju** [comment]
@gondimjoaom hey there! Thank you for reporting this.

What version of the app are you using? Also what operating system are you using (windows, linux, mac)?

**Comment by gondimjoaom** [comment]
Hi, appreciate the fast response!

I downloaded the 2.3.0 AppImage and I using it at Linux Mint 18.3.

I just saw that there is a new 2.3.1 update. Does it bring this option? Downloading it now anyway!

**Comment by ifedapoolarewaju** [comment]
@gondimjoaom yes it most likely fixes this issue now, as it now creates an external directory to store session cookies.

Please let me know if it works for you, so we can close this issue

**Comment by gondimjoaom** [comment]
It does not :(

I believe I did everything right as I **uninstalled the old AppImage and started using the 2.3.1 one**. But when I logout of Instagram I have to login back to my account when I open the program again.

Is there anything in the way of how a started using the new version? As i putted bold above.

**Comment by gondimjoaom** [comment]
Hey! I think I did something wrong when installing it. Or maybe I'm just dumb. I just opened your program and it was already logged in :)

Many thanks!
