### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by okaanarslann** [ifedapoolarewaju/igdm#597]
even if I confirm the entry from my instagram account I still get the same error urgently needs to be rectified help me pls

**Comment by jcgter777** [comment]
Yeah same here

**Comment by nicoboii** [comment]
Instagram call checkpoint for this action! #597 can someone please help fix this kind of issue. thanks!

**Comment by andriuwyepez** [comment]
Yo igual lo tengo. ningun desarrolador de la app o cfreador se comunica para solucionar esot?
