### ISSUE TITLE
Messages containing links

### ISSUE THREAD

**Issue by ifedapoolarewaju** [ifedapoolarewaju/igdm#6]
When a message contains links, it should be rendered such that the links would be clickable, and the url gets opened on the browser when clicked

**Comment by g8f6r4e7x2** [comment]
Would love to see this implemented :) Thank you.

**Comment by ifedapoolarewaju** [comment]
@g8f6r4e7x2 this has been implemented and released. :) Please visit https://ifedapoolarewaju.github.io/igdm/ to download, or if you are running the windows/mac versions, you can simply start the version you have and it would update itself :)

**Comment by ifedapoolarewaju** [comment]
fixed here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.1.0
