### ISSUE TITLE
Can't login : Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by jungfish** [ifedapoolarewaju/igdm#60]
OS - 10.12.6 and I don't have a 2FA :(

**Comment by threenator** [comment]
Same here

**Comment by IAMFBPT** [comment]
Having this same issue. Tried connecting both my laptop/phone to the same Wi-Fi network, confirming on my phone that I was trying to log in. Still getting the same error,

**Comment by batristio** [comment]
I had two factor authentication, which is not supported, so I turned it off. Still...can't log in, even though I am connected to the same wifi network - instagram call checkpoint for this action

**Comment by baptx** [comment]
There should be a functionality to enter a code to verify our identity like Instagram web version is doing for suspicious connections (they send a confirmation code by email).

**Comment by paul1454** [comment]
Same problem here ("Instagram call checkpoint for this action!"). Anyone been able to figure out a workaround to make it work? My computer was logged into the instagram web version when I tried to log in to IGDM and, thinking that might be the issue, I logged out of the web version, but am still running into the issue.

**Comment by paul1454** [comment]
Guys, found a solution searching the web. I tried it after my post earlier today and fixed the checkpoint issue.  Here is what I did:
===========
1. Login to your Instagram account on the web (you can do it on your computer or using the browser on your phone - I used chrome on my Pixel 2).

2. Click on the account profile icon

3. On your profile page, click the “Edit Profile” button

4. On the next page, scroll down to the bottom and click on the blue text “temporary disable my account”

5. Select “Just need a break” from the option why are you disabling your account? and enter your password. Then click on “Temporary Disable Account”

6. After that, wait for up to 3 hours (I waited a little over two hours and it worked)

NOTE: During the waiting period after you've disabled your account, make sure you DO NOT login to your account on any device (PC, tablet, smartphone, etc.)

7. After you've waited 2 to 3 hours, open IGDM on your computer and add login to  your Instagram account. Your account will be successfully added by now
================

Hope this helps. Good luck everyone.

**Comment by baptx** [comment]
I was able to use IGDM with the Instagram account that did not work before, there are 2 possibilities why it worked now:
- I used the Facebook login on the web version and then clicked on the "This Was Me" button (you have to use Facebook login, it did not work previously when I logged in with my password)
- I did not use the Instagram account for 1 or 2 weeks

**Comment by nicolajets1974** [comment]
tried that but still getting the same message.  unfortunately i don't have the correct phone with me today.  the one i have with me refuses to sign into instagram no matter what i try

**Comment by tatoline** [comment]
Success! I can logged into with using @paul1454 method. Thank you man.

**Comment by tyniasimone** [comment]
i cant log in please help

**Comment by tyniasimone** [comment]
i cant loggin into ig:dm

**Comment by tatoline** [comment]
> i cant loggin into ig:dm

Just use the @paul1454 's method. It worked for me buddy. [Here](https://github.com/ifedapoolarewaju/igdm/issues/60#issuecomment-406131637)

**Comment by avivas89** [comment]
Iniciando prueba de **paul454**

**Comment by odilonpsneto** [comment]
Hi guys! The solution seems to be easy. Open the browser and access the instagram.com - If the Instagram session in the browser is opened, end the session clicking in the exit (logout) button. 
After this step, open the IGdm and try login - the message will appear: "Checkpoint request".
Access again instagram.com and log in.
Switch to IGdm and try login again.

**Comment by onat007** [comment]
Just log out from all devices desktop, phone, tablet etc.. And open IGDM and login.. It's works for me..

**Comment by dm17** [comment]
So no, you don't need to disable two-factor. IGdm works with two-factor enabled. Logging out of the browser session of instagram fixed this issue for me.

**Comment by janak6625** [comment]
any logical solution available?  i try disabling my account and try to login with igdm still not working
