### ISSUE TITLE
upload pic to dm

### ISSUE THREAD

**Issue by ninjawesomee** [ifedapoolarewaju/igdm#61]
for some reason i cant upload any pics in the dms?? help plz

**Comment by ifedapoolarewaju** [comment]
The image upload experience has now been improved on [version 2.6.0](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.6.0)

**Comment by zauberbiene2** [comment]
i cannot upload images too it always say upload failed be ensure you file is in jpg format

**Comment by zauberbiene2** [comment]
> 
> 
> The image upload experience has now been improved on [version 2.6.0](https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.6.0)

i cannot upload images too it always say upload failed be ensure you file is in jpg format
