### ISSUE TITLE
error de internet

### ISSUE THREAD

**Issue by elkevin04** [ifedapoolarewaju/igdm#634]
buenas noches quisiera que arreglarar el error del wifi en igdm porque no me coge el internet y se queda trabado gracias por la atencion

**Comment by ifedapoolarewaju** [comment]
Hi so you are experiencing Wifi issues with IGdm? What error exactly do you experience

**Comment by Aly024** [comment]
Disconnects after a few moments
So every time I have to restart the program 

I run a instagram page So I find it very helpful
