### ISSUE TITLE
still instagram call on checkpoint

### ISSUE THREAD

**Issue by dhosheena** [ifedapoolarewaju/igdm#636]
nothing has been solved

**Comment by ifedapoolarewaju** [comment]
Hi @dhosheena, what version of the app are you running?

**Comment by dhosheena** [comment]
i think the 2.5 one

**Comment by ifedapoolarewaju** [comment]
2.5.3 or 2.5.2 or 2.5.1? Which?

**Comment by dhosheena** [comment]
i have downloaded the 2.5.3 ...and i am able to log in but the messages are not being delivered

**Comment by ifedapoolarewaju** [comment]
this message sending issue is now fixed in 2.5.4

**Comment by Leprosy** [comment]
I have 2.5.4, running it under Ubuntu 17.10 and I'm getting the same message.

**Comment by ifedapoolarewaju** [comment]
> I have 2.5.4, running it under Ubuntu 17.10 and I'm getting the same message.

do you see a prompt asking you for a verification code?

**Comment by dhosheena** [comment]
i am not able to open my instagram ..it is saying sentry instagram

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dhosheena** [comment]
i am not able to send messages

**Comment by ifedapoolarewaju** [comment]
what happens when you try to send a message?

**Comment by dhosheena** [comment]
i am not able to reply like to send a message

**Comment by dhosheena** [comment]
i am not able to get the message that 2 of my friends are sending me......
when i am entering the chat ...the messages are not loading..please do
something
