### ISSUE TITLE
Can't Switch Conversation and Messages Won't Send from One Account

### ISSUE THREAD

**Issue by andyhyon** [ifedapoolarewaju/igdm#654]
First off, really love this project, hope to contribute to it one day.
Second, don't mean to be a squeaky wheel and just wanted to document an issue I haven't seen reported yet - they could be related but figured any data points would be useful.

I have a few accounts and one of them won't let me switch to another conversation after attempting to send a message.

Repro steps:

1. Open up IGdm
2. Attempt to login and encounter 2FA
3. Successfully login (success rate ~80% of attempts)
4. Select a conversation
5. Attempt to send a message
6. Attempt to switch to another conversation

Expected Results: Message should go through (eventually) and allow me to select another conversation

Actual Results: Messages hang on "Sending..." and I'm not able to select another conversation

Notes: 2FA isn't enabled for both of my accounts but the offending account requires it for every instance of logging in.  IIRC, this account was created via linking with Facebook (if that matters). 

I'm still able to scroll through the conversation that IGdm froze on.

Hope this helps!

**Comment by LordTheuzim** [comment]
And that messages open in terminal
(node:12704) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AuthenticationError: Login required to process this request
(node:12704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
