### ISSUE TITLE
Error: read ECONNRESET on IG:dm

### ISSUE THREAD

**Issue by sarahm827** [ifedapoolarewaju/igdm#658]
Hello, 

Every time I try to login to my IG:dm -Instagram Desktop Messenger, it gives me an error "Error: read ECONNRESET" 

Please let me know what I need to do to fix this so I can log on. 

Thanks,
Sarah

**Comment by akxshitaaah** [comment]
yaa me too facing this problem! please tell me the solution for this problem....please 
thanks....waiting for answer

**Comment by HeavenC09** [comment]
I've been using IGDM for a while but It just started showing " Error: read ECONNRESET"  all of a sudden. I am currently using version 2.5.4 on a windows computer
