### ISSUE TITLE
will not let me log in

### ISSUE THREAD

**Issue by jokedout** [ifedapoolarewaju/igdm#663]
the app told said that an instagram call checkpoint was required to log in so i went to the instagram website and verified that it was me but ig:dm still wont tel me log in. please fix/help

**Comment by ifedapoolarewaju** [comment]
Hi there, please update to the latest version on http://igdm.me to fix this issue

**Comment by jokedout** [comment]
I did this and still had the same problem.

**Comment by ifedapoolarewaju** [comment]
What platform are you using? Windows? Linux? Mac? What version of the app are you running?

**Comment by jokedout** [comment]
Mac. I am attempting to use version 2.5.0 of your app

**Comment by ifedapoolarewaju** [comment]
You shouldn’t go to the website to confirm it’s you. You should rather receive a confirmation code in your email and use it in the code prompt you get on the app

**Comment by jokedout** [comment]
I have not received an email any of the times I have tried to log in. The screen I get is the log in screen for IG:dm says that there is an instagram call checkpoint for this action. I just tried again and it is not sending me an email.

**Comment by lucamengoni** [comment]
Hi, i have the same issue, version 2.5.4 for mac, i didn't receive the code after the login in my mail...

**Comment by VisheshSood** [comment]
I received the code and entered it but after that all I see is "Instagram call checkpoint for this action!"
