### ISSUE TITLE
Big Text Bug

### ISSUE THREAD

**Issue by rafaelvieiras** [ifedapoolarewaju/igdm#67]
When a message has a big text, the client does not show the text, only a message with content `<unsupported message format>`.

![image](https://user-images.githubusercontent.com/4449232/35065876-c43e8924-fbb5-11e7-9e66-d708618bada5.png)

**Comment by ifedapoolarewaju** [comment]
@rafaelvieiras Hi, what do you mean by big text?

**Comment by drigio** [comment]
@rafaelvieiras Hello, Instagram does not support DM messages bigger than 500 characters. [Maybe this can help you clear your doubt](https://www.quora.com/How-long-can-a-direct-message-be-in-Instagram)
