### ISSUE TITLE
Verification Code?

### ISSUE THREAD

**Issue by JoshiBaker** [ifedapoolarewaju/igdm#674]
Supposedly I've been sent an email with a verification code, but I haven't received any email at all? OS Windows 7

**Comment by ppizarror** [comment]
+1, using lastest version, windows 10

**Comment by apptrash** [comment]
+2 version from http://igdm.me/, windows 10

**Comment by ghotiandtchoghs** [comment]
same, it hasn't sent an email with a verification code, now what?
