### ISSUE TITLE
Instagram call checkpoint for this action

### ISSUE THREAD

**Issue by MrNotSoNice** [ifedapoolarewaju/igdm#681]
On a Windows 10, after entering in the code IG emails me, I keep getting "Instagram call checkpoint for this action!"  I have the 2 factor auth disabled.

**Comment by haleybear** [comment]
This is also an issue for Mac on Mojave.

**Comment by MrNotSoNice** [comment]
> 
> 
> This is also an issue for Mac on Mojave.

Its works on my Macbook.  Just not Windows 10.
