### ISSUE TITLE
Chats not loading

### ISSUE THREAD

**Issue by Patricus93** [ifedapoolarewaju/igdm#683]
Hello,

Having a small problem with the app using the Linux version. I'll send a message and the chat history will pop up, but if I leave the window for any reason (switch to a new one, minimize, etc) I loose the entire conversation. Same goes to logging in. I loose any and all history.

**Comment by ifedapoolarewaju** [comment]
how do you mean "you lose the entire conversation"? The chatlist becomes empty? It'd be very helpful if you could share a screenshot of this

**Comment by Patricus93** [comment]
![screenshot from 2018-10-19 21-27-18](https://user-images.githubusercontent.com/25761277/47221715-bb6a1d80-d3e7-11e8-8666-cfb035e05a87.png)

I can find people to message but the chats are not updated if people message me back and the screenshot above is what I always see when I log in or when i switch to another window.

**Comment by ifedapoolarewaju** [comment]
what version of igdm are you using?

**Comment by Patricus93** [comment]
2.5.4 x86 on Ubuntu 17.10

**Comment by angelbby81** [comment]
Same thing happening to me rn did u ever fix it?
