### ISSUE TITLE
npm errors - can't install

### ISSUE THREAD

**Issue by SirAkai** [ifedapoolarewaju/igdm#688]
x@x-kUbuntu:~/igdm$ npm start

> IGdm@2.5.4 start /home/sirakai/igdm
> gulp build && electron .

sh: 1: gulp: not found

npm ERR! Linux 4.15.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! IGdm@2.5.4 start: `gulp build && electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the IGdm@2.5.4 start script 'gulp build && electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the IGdm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs IGdm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls IGdm
npm ERR! There is likely additional logging output above.

**npm ERR! Please include the following file with any support request:
npm ERR!     /home/sirakai/igdm/npm-debug.log** (if u want I send u a link for the file or, in someway, the file)

I've downloaded the last version and done everything as instructions.

**Comment by ifedapoolarewaju** [comment]
Please run “npm i gulp” and try again

**Comment by adamac2** [comment]
npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! IGdm@2.6.5 start: `gulp build && electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the IGdm@2.6.5 start script 'gulp build && electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the IGdm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs IGdm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls IGdm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /XXX/igdm/npm-debug.log
===============================
I get this after following instructions and typing `npm i gulp`
