### ISSUE TITLE
Many accounts

### ISSUE THREAD

**Issue by Sanekmos** [ifedapoolarewaju/igdm#689]
Hello, dear team. Tell me please, is it possible to add several accounts to the program? I work in hotels and I have my instagram for each hotel. In the phone, I can do it, but in the program? Thank you !

**Comment by ifedapoolarewaju** [comment]
While this feature is not currently available on IGdm, please check out [IGdm Pro](https://pro.igdm.me) which has support for this feature and a few others

**Comment by ifedapoolarewaju** [comment]
closing as duplicate
