### ISSUE TITLE
Cannot install it!

### ISSUE THREAD

**Issue by atilav** [ifedapoolarewaju/igdm#69]
When try to install it, always get this message http://prntscr.com/i49fzv

It's a WIN version...

**Comment by janva255** [comment]
@atilav try running it on win 7 compatibility and execute as admin, that fixed it for me

**Comment by atilav** [comment]
@janva255 thanks for your reply.

Only have Windows 10.

**Comment by janva255** [comment]
@atilav nono, I mean right click on setup file, properties, compatibility tab, and then click on "run this program in compatibility mode for:" select windows 7 and in the bottom select the option "run this program as an administrator"

**Comment by atilav** [comment]
@janva255 

try  it http://prntscr.com/i4hyu8

but the same dialog box appears

**Comment by janva255** [comment]
@atilav oh, I'm sorry then, also, I discovered the official windows app for Instagram, which you can send messages in, https://www.microsoft.com/en-us/store/p/instagram/9nblggh5l9xt?source=lp

**Comment by atilav** [comment]
@janva255 no problem, thanks anyway for your support. All the best
