### ISSUE TITLE
Can't install on windows 10

### ISSUE THREAD

**Issue by janva255** [ifedapoolarewaju/igdm#70]
Tried with compatibility for win 8 and 7 but stops responding, in win 10 it doesn't do anything

**Comment by officialmmt** [comment]
Yep ++

**Comment by officialmmt** [comment]
Try with compatibility for win 7 and run as administrator

**Comment by janva255** [comment]
@officialmmt Thank you! that seems to work

**Comment by officialmmt** [comment]
Can you mark with solved please @janva255

**Comment by janva255** [comment]
@officialmmt isn't it better if it stays open? so people with the same problem can see the solution until it's fixed

**Comment by officialmmt** [comment]
They will think it is still problem @janva255

**Comment by Kirtz123** [comment]
I cant open it because it needs a 64 bit computer. Is there a download for a 32 bit computer?

**Comment by juwiepie** [comment]
![capture](https://user-images.githubusercontent.com/42560645/44377079-d7f3f180-a52d-11e8-92b8-d7541a8dc3fb.PNG)
its stuck like this

**Comment by Sumit9936** [comment]
![capture](https://user-images.githubusercontent.com/45148986/48676004-7bcd5780-eb86-11e8-983c-de84d7c4a245.PNG)

what do I do?

**Comment by virmanue** [comment]
![Captura](https://user-images.githubusercontent.com/83567262/116841187-6c9bc200-aba6-11eb-84c5-2336262bd8f4.PNG)

**Comment by virmanue** [comment]
![Captura](https://user-images.githubusercontent.com/83567262/116841215-82a98280-aba6-11eb-897f-3c5914ee3d92.PNG)
Hello. please help..
