### ISSUE TITLE
No verification code 

### ISSUE THREAD

**Issue by MoonNation** [ifedapoolarewaju/igdm#705]
I tried using the Instagram DM App but haven't been able to log in because it ask for a verification code I never get. I've checked all of my spam folders and what not but I cant find anything. Just want to make sure I wasn't just looking in the wrong location. Thank you.

**Comment by JoshiBaker** [comment]
+1, using Windows 7, made an issue about this over a month ago and no reply yet :/

**Comment by ben10565** [comment]
im using Linux Ubuntu and whats up guys why you didnt solve this problem?
