### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by niyahhh** [ifedapoolarewaju/igdm#709]

**Comment by gabriellecozart** [comment]
Also having this issue. I got the verification email and gave the code the app asked for, it it said in red "Instagram call checkpoint for this action!". I click log in then it loads and does nothing. I am running on OSX Mojave.

**Comment by Miguel7113** [comment]
Having the exact same issue. However i am running on Windows 10

**Comment by tuanluu-agilityio** [comment]
`Instagram call checkpoint for this action!`
Same issue when login, please  follow [issue 60](https://github.com/ifedapoolarewaju/igdm/issues/60) for more detail
