### ISSUE TITLE
<unsupported message format>

### ISSUE THREAD

**Issue by rohangupta3** [ifedapoolarewaju/igdm#712]
This message keeps coming up on igdm

**Comment by ppkozlowski** [comment]
Unfortunately, I don't know which type of message you've received. For me most of the cases are raven_media. I've created simple reven_media renderer to handle expiring photos.

**Comment by PayneLessDesigns** [comment]
Just thought I would try IG:dm. I, too, am getting some parts of the messages saying "unsupported format" in your latest version. Some are messages I sent. Some are messages received. One showing unsupported format was all text. No images or videos in it. Some showing this message was between photos that were sent. Not a problem for me as I am just trying out your program. Thought you might like to know latest version is having same problem. Doubt if attached photo file is of any help.

**Comment by TDGalea** [comment]
I can say that one of these <unsupported message format>s is the liking of messages (double tap a message in the Instagram app and it leave a heart; same as comments). Doing this results in a <unsupported message format> message appearing in IG:dm.

**Comment by rohangupta3** [comment]
Ok thanks, is there a way you could show the heart instead of the message?
Rohan
 

    On Tuesday, 21 May 2019, 19:44:31 BST, TDGalea <notifications@github.com> wrote:  
 
 
I can say that one of these s is the liking of messages (double tap a message in the Instagram app and it leave a heart; same as comments). Doing this results in a message appearing in IG:dm.

**Comment by Jak00711** [comment]
Hello, Thank you for this great solution. 
It still shows **<unsupported message format>** in pro version and **<unsupported message format: video_call_event>** in a normal version.

Is this error already fixed? if not, could you tell me in which file i can find this **video_call_event** , so i can try to fix it?

Thank you!!

**Comment by someone857** [comment]
`renderer.js`
from this app perspective, i think the best we can do is display a message like _video call incoming, answer on your phone_
please avoid bumping old threads. if you will tackle this, open a new issue. thanks

**Comment by rohangupta3** [comment]
It has now been fixed.
Rohan
 

    On Monday, 20 April 2020, 08:37:21 BST, Jak00711 <notifications@github.com> wrote:  
 
 


Hello, Thank you for this great solution.
It still shows  in pro version and  in a normal version.

Is this error already fixed? if not, could you tell me in which file i can find this video_call_event , so i can try to fix it?

Thank you!!
