### ISSUE TITLE
I don't receive verification code on my email.

### ISSUE THREAD

**Issue by Shemenaserg** [ifedapoolarewaju/igdm#713]
Sorry, I need your help! I don't receive verification code on my email. What can I do?
shemenaserg@gmail.com

I even checked the spam, it's also empty

**Comment by Shemenaserg** [comment]
Sorry, I just receiwe it. But I sould whait about 0,5h

**Comment by nabyle** [comment]
>
> *resend your User name & pass word i will resolve your problem very soon*
>
>
Le mar. 6 nov. 2018 à 15:36, Shemenaserg <notifications@github.com> a
écrit :
