### ISSUE TITLE
Lovely App

### ISSUE THREAD

**Issue by spiketrain** [ifedapoolarewaju/igdm#715]
So glad you've thrown this app together.... am really hoping to use it soon

I noticed that, once signed in, you don't seem to be able to sign out. I have four Instagram accounts I would probably use this for... So I was wondering if you might be challenged to have a hot swap feature so I can dive across multiple accounts one day.

In the meantime - well done and thank you again. Really hoping this comes in handy.

**Comment by ifedapoolarewaju** [comment]
While this feature is not currently available on IGdm, please check out [IGdm Pro](https://pro.igdm.me) which has support for this feature and a few others

**Comment by ifedapoolarewaju** [comment]
closing as duplicate
