### ISSUE TITLE
Problems whe close the app

### ISSUE THREAD

**Issue by federicosnobohm** [ifedapoolarewaju/igdm#73]
when in close the app IGDM i always have to login in. please fix it

thanks

**Comment by ifedapoolarewaju** [comment]
@federicosnobohm what version do you use? Also what OS do you run?

**Comment by federicosnobohm** [comment]
i use linux deepin os 15.5 and the IGDM 2.3.0 version


________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 03:06 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)


@federicosnobohm<https://github.com/federicosnobohm> what version do you use? Also what OS do you run?

**Comment by ifedapoolarewaju** [comment]
please install the latest version from here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.3.1 this issue was fixed there

**Comment by federicosnobohm** [comment]
thanks but whats installer i must choose of the list?
________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 03:20 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)


please install the latest version from here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.3.1 this issue was fixed there

**Comment by federicosnobohm** [comment]
this says cant open the packpage :( deepin is based on debian
________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 04:14 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)


here https://github.com/ifedapoolarewaju/igdm/releases/download/v2.3.1/IGdm-2.3.1-x86_64.AppImage

**Comment by ifedapoolarewaju** [comment]
How and from where did you installed the current version you running?

Ifedapo Olarewaju  | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by federicosnobohm** [comment]
From the Deepin Store
________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 06:11 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)

How and from where did you installed the current version you running?

Ifedapo Olarewaju | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by ifedapoolarewaju** [comment]
Can you follow the steps here https://unix.stackexchange.com/a/379353 <https://unix.stackexchange.com/a/379353> to make it executable, and then try to run it?

Ifedapo Olarewaju  | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by federicosnobohm** [comment]
thanks but not found


________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 07:02 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)

Can you follow the steps here https://unix.stackexchange.com/a/379353 <https://unix.stackexchange.com/a/379353> to make it executable, and then try to run it?

Ifedapo Olarewaju | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by ifedapoolarewaju** [comment]
what do you mean not found? The URL returned a 404?

Ifedapo Olarewaju  | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by federicosnobohm** [comment]
No. When i run The file This says 'this Packpage is Not compatible'
________________________________

**Comment by federicosnobohm** [comment]
thank you for your support! now i can run the fixed version.


________________________________
De: Ifedapo .A. Olarewaju <notifications@github.com>
Enviado: miércoles, 24 de enero de 2018 07:51 p.m.
Para: ifedapoolarewaju/igdm
Cc: federicosnobohm; Mention
Asunto: Re: [ifedapoolarewaju/igdm] Problems whe close the app (#73)

what do you mean not found? The URL returned a 404?

Ifedapo Olarewaju | Software Developer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by ifedapoolarewaju** [comment]
> thank you for your support! now i can run the fixed version.

could you please share how you fixed it, for future reference?

**Comment by federicosnobohm** [comment]
With The latest instructions That you send me of The web
