### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by LordManhattan** [ifedapoolarewaju/igdm#752]
Now, this is far from the first reported case of this, and it's apparent that a lot of people are having issues with notifications. This is probably the second or third time I install this app, and it works okay, but I'm not receiving any notifications, making me have to check the app periodically to see if people have written anything. 

This isn't something that I'm interested in continuing doing on a daily basis, so it would be nice if someone around here knows what's up. 

- Windows 10 Pro 1803
- Microsoft Surface Laptop
- No restrictive policies or settings in place

Thanks in advance

**Comment by kellymendozac55** [comment]
I need to know my code

**Comment by ClwnMan76** [comment]
@LordManhattan Did you ever get it fixed?
