### ISSUE TITLE
source code for windows version

### ISSUE THREAD

**Issue by fzs001** [ifedapoolarewaju/igdm#756]
Are there source codes for windows version?

**Comment by ifedapoolarewaju** [comment]
> Are there source codes for windows version?
what do you mean by source code for windows version exactly?

**Comment by paltrickontpb** [comment]
@fzs001 Electron is a cross platform desktop application building library. The given source-code will work on windows, linux and darwin.

@ifedapoolarewaju Please do close the issues, there are significant number of issue already..
