### ISSUE TITLE
Log in Error

### ISSUE THREAD

**Issue by fe1ipe1emos** [ifedapoolarewaju/igdm#763]
Just couldn't log in, here's the error:

Error: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:827:

**Comment by ifedapoolarewaju** [comment]
are you using a vpn or a proxy
