### ISSUE TITLE
Turn off autoupdate

### ISSUE THREAD

**Issue by puriabestia** [ifedapoolarewaju/igdm#768]
Is there a way to turn off autoupdating? 
(2.5-2.6 is segfaulting)

**Comment by ifedapoolarewaju** [comment]
Hi what machine are you using? Apple? Windows? Linux?

**Comment by puriabestia** [comment]
Linux.

**Comment by ifedapoolarewaju** [comment]
Hi, the segfault issue is fixed in version 2.6.1, please update and confirm :)
