### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by ifedapoolarewaju** [ifedapoolarewaju/igdm#77]

**Comment by bankks** [comment]
Heya! Let's do this! 
To start it, I was thinking about some general details like some backgrounds, spacements and typographs.
Also get more close of what Instagram direct message visual looks like on mobile, using the same branding, font, colors and everything.
Aaaaand an amazing new Icon app :)

**Comment by ifedapoolarewaju** [comment]
yes please, I'm super pumped about this 😁

**Comment by drigio** [comment]
@bankks @ifedapoolarewaju Maybe even have changes to the Instagram DM website too? With much more attractive UI :)

**Comment by bankks** [comment]
@drigio yep, it's on my roadmap as well!! 😃🚀
After we have a better branding like the icon and new screenshots I'll create a new landing page for the app :)

**Comment by udiudiudiudi** [comment]
the main issue i think is the logo, its too dark

**Comment by bankks** [comment]
@ifedapoolarewaju @drigio @udiudiudiudi 
Hey guys, I'm more stable now with my new home, job and stuff and I was starting to try some improvements on the IGdm.
I was editing and saving my changes on the code, but how do I see it?
Do I need to run 'npm start' again? 
There's anyway to run the application locally on my browser ? So I can test and use the dev tools to debug and test my modifications?

Thanks!

**Comment by ifedapoolarewaju** [comment]
@bankks if your changes are just UI changes, you are can do `CMD+R` or `CTRL+R` to refresh. To view the dev console, you can use the normal keyboard shortcut used to open for chrome.

**Comment by bankks** [comment]
@ifedapoolarewaju Oh I got it! It was my first time using electron, and it worked!
Amazing! Let's do this! 😀

**Comment by ifedapoolarewaju** [comment]
@bankks also please note that there was a UI related PR that got submitted some weeks back, and this already did a lot of cleanups and gave a nicer look.
https://github.com/ifedapoolarewaju/igdm/pull/87

cc @ciolt
