### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ivanpoo** [ifedapoolarewaju/igdm#774]
When i try to attach a photo, it won't send, although its is a .jpg file; I also cannot see some images that people send to me

**Comment by SHIELD22** [comment]
I just got the same Problem the version before last had the new  uploading .jpg the 6.2 slams it with an error please make sure you're useing .jpeg   it's .jpg

**Comment by mruncleleon** [comment]
When I download a photo from internet and cannot send on IGdm I try to open in MSPAINT and Save As .jpeg

**Comment by hydsmitten** [comment]
i have the same issue, any solution
