### ISSUE TITLE
problem with logging in igdm desktop

### ISSUE THREAD

**Issue by maheshraju99** [ifedapoolarewaju/igdm#78]
i am not bl to logging in igdm desktop with my instagram account

**Comment by fidelisrafael** [comment]
Can you give more details?

**Comment by fidelisrafael** [comment]
It's this related with #76 ?

**Comment by myhweissman4515** [comment]
I cannot log in I have tried the solution of temporarily suspending the account and I still got error of "not possible to parse api response"
