### ISSUE TITLE
Cannot install on windows 7

### ISSUE THREAD

**Issue by mpaezt** [ifedapoolarewaju/igdm#784]
Hi,

I run the installer and it does run but when I tried to run the app installed, it does nothing. I tried to run it as administrator but the same happened.

OS: Windows 7 Professional SP1
IGdm v2.6.1

Please, your help.

Thank you in advance!

**Comment by ifedapoolarewaju** [comment]
I cannot guaranty a windows 7 support. Could please try installing an older version?
