### ISSUE TITLE
Official download from https://igdm.me for windows contains malware

### ISSUE THREAD

**Issue by ackstorm23** [ifedapoolarewaju/igdm#787]
![igdm malwarew](https://user-images.githubusercontent.com/20215703/51207987-fc33de80-18d1-11e9-8337-13af1702e338.png)

**Comment by ackstorm23** [comment]
I downloaded this three times from the official https://igdm.me windows download link, and each time it came back with this malware detected.

**Comment by ackstorm23** [comment]
interestingly the pro version of this product does not contain the malware, only the free version.

**Comment by Yoldrim** [comment]
I ran it through [VirusTotal](https://www.virustotal.com/#/file/d1b7e6b7d50e9a59d1934f55b8e10dda87f7180723a7286138e4eff05b0ba972/detection), doesn't seem to contain any malware (HW32.Packed seems to be a common false-positive).

**Comment by ifedapoolarewaju** [comment]
this is merely a false positive from the antimalware app
