### ISSUE TITLE
my igdm is not working and is saying instagram call checkpoint for this action

### ISSUE THREAD

**Issue by Spaceraiderjosh** [ifedapoolarewaju/igdm#788]

**Comment by jagl06** [comment]
Im having the same error, when i log in my IG acc ask if was me trying to login i said yes and looks like IG dont authorize the IGDM log.

appreciate any suggestions.

**Comment by juleto** [comment]
I'm having the same issue with `IGdm-2.6.1-x86_64.AppImage`
![2019-01-20-212614_1680x1050_scrot](https://user-images.githubusercontent.com/34169391/51447247-e3c12b00-1cfa-11e9-9383-9ee57a750cf4.png)

**Comment by ifedapoolarewaju** [comment]
closing as duplicate
