### ISSUE TITLE
Unable to Install in WIN 7

### ISSUE THREAD

**Issue by Rokuh** [ifedapoolarewaju/igdm#79]
The setup doesn't start in WIN 7 at all. Keeps throwing this again and again...

![2313121](https://user-images.githubusercontent.com/36113195/35770708-4a404bc8-0946-11e8-8702-6fa710886fa6.png)

Any help?

**Comment by ifedapoolarewaju** [comment]
closing as duplicate of this https://github.com/ifedapoolarewaju/igdm/issues/52
