### ISSUE TITLE
<unsupported message format>

### ISSUE THREAD

**Issue by magician11** [ifedapoolarewaju/igdm#80]
Hi guys,

I see in my conversations `<unsupported message format>` appear from time to time.

I think what's happening is when someone likes my message in the Instagram app, it shows this message in this app.

Is this a known issue? Does this sound right?

**Comment by ifedapoolarewaju** [comment]
yes it's a known issue, but thanks for reporting anyways 🙂

**Comment by rafaeldsampaio7** [comment]
olá estou tento problema no meu instagram no direct pelo aplicativo do pc de <unsupported message format> como posso resolver.
agradeço se puder ajudar

**Comment by rafaeldsampaio7** [comment]
olá estou tendo problema no meu instagram no direct pelo aplicativo do pc de <unsupported message format> como posso resolver.
agradeço se puder ajudar

**Comment by rafaeldsampaio7** [comment]
Hello guys
I'm having a problem in my instagram direct via pc
<unsupported message format>
thank you if you can help

**Comment by rafaeldsampaio7** [comment]
<unsupported message format>

**Comment by rafaeldsampaio7** [comment]
Oi pessoal,

Eu vejo em minhas conversas <unsupported message format>aparecem de vez em quando.

Eu acho que o que está acontecendo é quando alguém gosta da minha mensagem no aplicativo Instagram, ele mostra esta mensagem neste app.

Isso é um problema conhecido? Isso soa certo?

**Comment by rafaeldsampaio7** [comment]
<formato de mensagem não suportado>
