### ISSUE TITLE
It's a bit laggy.

### ISSUE THREAD

**Issue by 2AroBaticCats** [ifedapoolarewaju/igdm#802]
If it would send, receive, and show read faster that would be great. And if it showed the typing bubble that'd be way cool too. Other than that, it's great I love it.

**Comment by ifedapoolarewaju** [comment]
What version of IGdm are you using? The latest version is pretty fast

**Comment by 2AroBaticCats** [comment]
The latest, 2.6. I'm using windows so idk if that changes anything.
