### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by A1mSh1k** [ifedapoolarewaju/igdm#803]
Hello! I can not log in to your application. What should I do?

**Comment by fatiii03** [comment]
Quiero que me funcione el instagaram direct por una vez yaaaa!!!

**Comment by gaverson** [comment]
i caonnot login//

**Comment by ifedapoolarewaju** [comment]
@gaverson what happens when you try to login?

**Comment by gaverson** [comment]
> @gaverson what happens when you try to login?

once app upgraded and after that i logined in the app, but o got a error with text "EPERM: operation not permitted, open 'C:\Users\Gaver\AppData\Roaming\IGdm\session-cookie\and.gaver.json'"

**Comment by alifakbarsyah** [comment]
same here , need help
