### ISSUE TITLE
cant log on, gettin message "Instagram call checkpoint for this action!"

### ISSUE THREAD

**Issue by burlcone** [ifedapoolarewaju/igdm#804]
I've been trying to log in from my home computer on which I use Chrome to access Instagram but I am getting the message "Instagram call checkpoint for this action!".   I do not have two-factor authentication enabled and I am not seeing any prompt in the app on my phone for verification nor am I getting a verification email.  I'd like to try this program and I'd be very likely to buy the pro version if I can get it working.  I'd also be glad to be a beta tester for future versions.  If you'd like me to reply further here or by email please let me know.

**Comment by mircolac** [comment]
Same problem here. I noticed that on the instagram website it detects an anomalous access after trying to log in. After choosing 'ok, it was me', nothing changes. Help!

**Comment by ptofevski** [comment]
Same here I just downloaded the app and I tried to login, it gave me "Instagram call checkpoint for this action!". I clicked on my phone "It was me" but nothing changes.

**Comment by SpektrEG** [comment]
Works for me on IGdm 2.5.3

**Comment by burlcone** [comment]
Hi, I tried to log in again today and for the first time I got some sort of "autoupdate" pushed for the IG:dm app.  Even after the update I still can't log in with the app.  I am running Windows 10 professional 64 bit with an Instagram account that has no issues, I use the account regularly with no issues on the web, on the Windows 10 Instagram app, and on my phone.   I am still getting a "Instagram call checkpoint for this action" message when I try to log in with IG:dm but I get no prompt to do anything on the Instagram website or the app on my Android phone or the Windows 10 app, nor do I get any message sent to the account's email or phone number alerting me to anything.  I dont have two factor authentication enabled.  There are no system issues with Instagram now or anytime in the last few days or at any time I've had these issues before.  What more can I do to possibly fix this?

**Comment by burlcone** [comment]
We'll someone just closed this issue thread and I'm not sure why. I still can't log in and I looked at the other threads referenced in the first reply above its particular number 8:03 and not have any suggested actions for me to take it all.  Any suggestions would be appreciated thanks again!

**Comment by ifedapoolarewaju** [comment]
Hey, sorry I closed this because it's a duplicate issue. There a number of similar issues on this repo.

Per this issue you are facing, it sometimes happens because IG detects the login as an unusual one. It's quite erratic, and not easy to solve. What works sometimes is to logout from the browser and login again, then restart the IGdm app and try to login on there again.
