### ISSUE TITLE
Feature to export messages with specific user

### ISSUE THREAD

**Issue by nklipa13** [ifedapoolarewaju/igdm#806]
As title said, I believe that it isn't big problem as you already are able to see all messages, so maybe it would be cool if you can export messages with specific user as json, or something like that. I know that Instagram now gives option to export all data, but you need to wait up to 48h and sometimes you just need it as soon as possible

**Comment by ifedapoolarewaju** [comment]
closing as duplicate to https://github.com/ifedapoolarewaju/igdm/issues/832
