### ISSUE TITLE
Icons it does not work

### ISSUE THREAD

**Issue by soyrcom** [ifedapoolarewaju/igdm#809]
The icons not work in windows 7 ultimate x64B Bits in the actually version of igdm
http://prntscr.com/mngtsj

**Comment by cuti7x** [comment]
me too
![screenshot-bpconcjcammlapcogcnnelfmaeghhagj-2019 05 18-09-11-37](https://user-images.githubusercontent.com/50139199/57963531-99ba2000-794f-11e9-835e-e52a5722ee8b.png)
