### ISSUE TITLE
[SUGGESTION] Possible workaround for the rampant login issues 

### ISSUE THREAD

**Issue by Mintonne** [ifedapoolarewaju/igdm#811]
Hello @ifedapoolarewaju,

I stumbled on this repo while looking for the best way to handle logging into an Instagram account from Electron.js.

I believe I have found the best way to do so without requesting for any credentials (username, password etc).

Electron [supports](https://electronjs.org/docs/api/webview-tag) Chrome [webviews](https://developer.chrome.com/apps/tags/webview). You can create a webview for the login page and let Instagram handle all the login and verification procedures.

```js
<webview src="https://www.instagram.com/accounts/login/" style="height: 100%; width: 100%" />
```

The cookies seem to persist even after you close the application but in case you need to manual save them, you can [easily do so](https://electronjs.org/docs/api/cookies#class-cookies).

I haven't gone through your code thoroughly but the few bits I checked, this does seems like a viable solution.

**NOTE**

Electron webview warning

>Electron's webview tag is based on Chromium's webview, which is undergoing dramatic architectural changes. This impacts the stability of webviews, including rendering, navigation, and event routing. We currently recommend to not use the webview tag and to consider alternatives, like iframe, Electron's BrowserView, or an architecture that avoids embedded content altogether.

I really don't think the core functionality will change.

---

IFrame is also another workaround. I haven't tried it but it seems viable. You will need to get rid of the X-FRAME-OPTIONS header though for it to work.

[IFrame & X-FRAME-OPTIONS header](https://github.com/electron/electron/pull/573)

**Comment by ifedapoolarewaju** [comment]
this won't work because we are not using the web app API ... instead, we are using the API used by the mobile apps

**Comment by Mintonne** [comment]
Aaah! Okay.

Just saw the code that handles the authentication and it is indeed very different.

There is still hope though - https://techcrunch.com/2019/02/12/instagram-direct-desktop/

**Comment by ifedapoolarewaju** [comment]
yes but this is indefinite for now
