### ISSUE TITLE
Automated Dms

### ISSUE THREAD

**Issue by awesome205** [ifedapoolarewaju/igdm#813]
Hi All,

Is there a way to automate the dms so you can send a welcome dm to people who follow you?

If not, would anyone like to help me create one - I am pretty skilled in python and Java so I think ill be able to make it I'm just not sure how to start.

Thanks!

**Comment by Joyen12** [comment]
Hi @awesome205 ,
Did you success in doing this ? Because I am also interested in this function but same as you.
I can't find it and not sure where to start to code it...
