### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by VeljkoFX** [ifedapoolarewaju/igdm#823]
![Capture](https://user-images.githubusercontent.com/48518309/54278939-14ec0800-4594-11e9-99a8-2c88126ea417.JPG)

**Comment by cavi21** [comment]
This is an issue in IG, you can check that their service is experiencing [outages](https://outage.report/instagram)

**Comment by chihailing** [comment]
I use my Ins credentials,But I can't  login,Please give me a solution.
