### ISSUE TITLE
NONE OF MY TEXT ARE SENDING!! IG DM HELP

### ISSUE THREAD

**Issue by mariah535** [ifedapoolarewaju/igdm#825]
NONE OF MY TEXT ARE SENDING AND I NEED TO BE ABLE TO SEND MESSAGE!!!

**Comment by mariah535** [comment]
NO THAT DID NOT HELP AT ALL

**Comment by cavi21** [comment]
This is an issue in IG, you can check that their service is experiencing [outages](https://outage.report/instagram)
