### ISSUE TITLE
Not possible to parse API response - please read

### ISSUE THREAD

**Issue by miniatvre** [ifedapoolarewaju/igdm#826]
I know there's been multiple posts about this already but I was trying to message a person and it showed that the same message had been sent to this twice so I figured if I just log out and log back in, it would refresh it and everything would be fine. After trying to log in it gives me the Not possible to parse API response error and it won't let me sign on to instagram.com either. I haven't really seen any other replies to other post and I was just wondering if this is a issue that will get fixed on its own or if I should actually be concerned about not being able to log into any of my accounts? if someone would actually reply it would be much appreciated. thank you

**Comment by cavi21** [comment]
This is an issue in IG, you can check that their service is experiencing [outages](https://outage.report/instagram)
