### ISSUE TITLE
I CAN'T DO ANYTHING!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by freak9102** [ifedapoolarewaju/igdm#828]
I have been trying to text people but it will take forever to send. It also didn’t want to let me sign in. I had to keep spamming the login to Instagram button to finally get in. Can you please explain to me what’s going on? And how I can update the app? You guys are literally no help. @ifedapoolarewaju you made this app so why aren't you helping solve the problem. The robot doesn't help us resolve the problem. All it does is tell us our problem is the same as other peoples. Please solve the problem.

**Comment by cavi21** [comment]
This is an issue in IG, you can check that their service is experiencing [outages](https://outage.report/instagram)
