### ISSUE TITLE
Liked messages aren't displayed correctly

### ISSUE THREAD

**Issue by kodburn** [ifedapoolarewaju/igdm#830]
Whenever someone like a message in the chat, I receive "unsupported message format" message.
Thanks

**Comment by ylaan** [comment]
I'm getting the same issue. When messages are "liked" it displays "<unsupported message format>" in the following text bubble. 
<img width="781" alt="Screen Shot 2019-08-06 at 11 45 00 AM" src="https://user-images.githubusercontent.com/36427442/62567238-a6a82a80-b83f-11e9-99b9-850c66dcb7e5.png">

Expected Result: When a message is liked, it should show who liked it and not display another text bubble "<unsupported message format>"

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed in the latest version
