### ISSUE TITLE
Igdm not working properly

### ISSUE THREAD

**Issue by arushi33** [ifedapoolarewaju/igdm#85]
I am chatting with my friend and did not had any kind of issue for some days but now when I opened it all my chats were deleted and when I searched my friends username nothing is coming.
please look into the issue and solve it as soon as possible.

**Comment by ifedapoolarewaju** [comment]
@arushi33 Hi, can you confirm that this is not the case on the mobile application too? It could be that, the user had been blocked, or suspended or some other issue from instagram itself

**Comment by arushi33** [comment]
I am searching their usernames also still nothing is coming

**Comment by ifedapoolarewaju** [comment]
yes, this is why I suspect that the user might have been suspended. Are you able to search on the mobile app? If you can't find anything, then the user might have been suspended

**Comment by arushi33** [comment]
this is me..
