### ISSUE TITLE
Enter keys not working

### ISSUE THREAD

**Issue by lexiedree** [ifedapoolarewaju/igdm#850]
Hello! It appears when someone sends me a media message, I cannot see it nor reply back, as I type a response and click enter, it only begins a new line. I've tried plugging in a new keyboard, reinstalling and uninstalling and still nothing. I messaged someone else that hadn't sent me a media message and it worked just fine.

**Comment by JustinPoe** [comment]
To augment this issue, which I too am now seeing, I notice that the last activity was my sending a media message.  So, it appears to arise following either receipt or sending of media messages.
