### ISSUE TITLE
Consent Required! Unable to login.

### ISSUE THREAD

**Issue by sTiKyt** [ifedapoolarewaju/igdm#855]
# consent_required
Unable to login, have this error:
![image](https://user-images.githubusercontent.com/35602029/55481731-ad255c00-562b-11e9-9486-b53edcc5bc0a.png)

**Comment by ifedapoolarewaju** [comment]
yes this issue appears because instagram is requiring you to update your date of birth possibly. You need to do this on the mobile app, and then try to login on Igdm again

**Comment by sTiKyt** [comment]
@ifedapoolarewaju my phone dead, i can't use it -_-

**Comment by ifedapoolarewaju** [comment]
I'm afraid there's no other workaround for this issue. This age consent thing was recently added to IG, and it requires that you set your date of birth before you continue using instagram.

**Comment by sTiKyt** [comment]
@ifedapoolarewaju I'm afraid i fixed it just second ago.. 
Just logined using web browser and problem was solved...
