### ISSUE TITLE
Mesaj Sorunu

### ISSUE THREAD

**Issue by Suderya** [ifedapoolarewaju/igdm#858]
IGdm adlı bilgisayar uygulaması olan uygulamada sorun yaşıyorum. Bir kullanıcıya attığım mesaj bir başkasına gidiyor, önceki bir kaç mesajlaşmamız gözükmüyor. Düzeltilmesini rica ediyorum acilen.

**Comment by MC117243** [comment]
@Suderya 
Programi, Kaldirip, yenidan koy mayi calis.

Translation to what he said:
When he sends a message it doesn't go to who he wants it to go to, rather to someone else. Also he can't see a couple of the previous messages in that conversation. He would like it fixed.
