### ISSUE TITLE
Write the API description

### ISSUE THREAD

**Issue by nilrequire** [ifedapoolarewaju/igdm#86]
Hi😉
You have the best app. But can you create a .md file with with description URI methods which you use ?

**Comment by ifedapoolarewaju** [comment]
Hello @nilrequire most of the uri methods used on IGdm are more from [this library](https://github.com/huttarichard/instagram-private-api/). So basically reading the docs of that should suffice 🙂

Otherwise, requesting for API docs from there would also suffice 🙂 

Does this answer your question?

**Comment by nilrequire** [comment]
Yes, thanks 😉
