### ISSUE TITLE
Error in today's update

### ISSUE THREAD

**Issue by janak6625** [ifedapoolarewaju/igdm#860]
![Untitled](https://user-images.githubusercontent.com/48966018/55503058-83603b00-5613-11e9-88fb-56e1de430be8.png)
App is totally not working when i update today, before image upload is not working, not its not working at all

**Comment by janak6625** [comment]
why his issue is closed without solution ?

**Comment by ifedapoolarewaju** [comment]
The issue os fixed, please update to the latest version
