### ISSUE TITLE
Problem whit the chat

### ISSUE THREAD

**Issue by trilloo** [ifedapoolarewaju/igdm#867]
when i send a message to a particular person the message is sent to another person that i don,t wanna send it

**Comment by Puresaam** [comment]
> when i send a message to a particular person the message is sent to another person that i don,t wanna send it

same problem:(( i dont know what to do

**Comment by ifedapoolarewaju** [comment]
@Puresaam this issue ought to be fixed in the latest version (2.6.4). What version are you using?

**Comment by trilloo** [comment]
version 2.6.4 i try to reinstalling the program and now it seems that works right Thanks
