### ISSUE TITLE
my Ig:dm is not working

### ISSUE THREAD

**Issue by aevlin** [ifedapoolarewaju/igdm#869]
a group chat I'm in isn't allowing me to access the newer messages or content of the chat nor will it let me text in said chat. whenever i try to (i even tried uninstalling and re-installing ) it sends the message to another person in my dms. same with other people in my dms. please fix this bug and or make a newer version with more features. id say 3.5/4.0 but overall great app!

**Comment by aevlin** [comment]
u have to fix it as soon as possible

**Comment by aevlin** [comment]
![d](https://user-images.githubusercontent.com/49306328/55618739-da514600-57b4-11e9-9320-dbf7e6f5974f.JPG)

**Comment by miniatvre** [comment]
yeah that's exactly what mine is doing too. can't even use it anymore

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update
