### ISSUE TITLE
Messages Switching

### ISSUE THREAD

**Issue by yeetdes** [ifedapoolarewaju/igdm#871]
When I try and send a message to someone it did not show up and then when it sent it sent to the other person in my DM's and it wont send to the person , im not blocked , I reinstalled and updated the app but it still switches message directory when I send one , pls help !

**Comment by ifedapoolarewaju** [comment]
Hi could you please help me understand how to fix this? What are the steps to reproduce this?

**Comment by Puresaam** [comment]
> When I try and send a message to someone it did not show up and then when it sent it sent to the other person in my DM's and it wont send to the person , im not blocked , I reinstalled and updated the app but it still switches message directory when I send one , pls help !

I have exactly the same problem. I need this to get fixed as soon as possible.

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update
