### ISSUE TITLE
Igdm

### ISSUE THREAD

**Issue by Tavies04** [ifedapoolarewaju/igdm#872]
I was going to log into one of my accounts with that and i know it has to send a security code but it never sent me one to my email when i tried to log in and now i cant log in even on the regular app is there any way ya'll can fix that.

**Comment by Tavies04** [comment]
thx i looked at all of those but non of them was related to what i needed but thx for the predictions.

**Comment by ifedapoolarewaju** [comment]
what happens when you try to login on the mobile app?

**Comment by Tavies04** [comment]
Hey I figured it out but thanks for responding😁
