### ISSUE TITLE
IGDM

### ISSUE THREAD

**Issue by Puresaam** [ifedapoolarewaju/igdm#876]
On IGDM I cant send messages to only one specific account. I need this to get fixed as soon as possible. Thank you.

**Comment by kylerchin** [comment]
![image](https://user-images.githubusercontent.com/7539174/55677746-4067c700-58a2-11e9-95d1-ffc0510fafd6.png)

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update
