### ISSUE TITLE
Get stuck rendering old messages

### ISSUE THREAD

**Issue by serniko97** [ifedapoolarewaju/igdm#877]
The function renderMessages(); in renderers.js seems to get stuck with some inward messages.
Apparently some inward messages have a weird message._params.accountId that doesn't mate with account.id in window.chat.accounts.find();
I'll try to fix it later because I'm having issues with node.

**Comment by ifedapoolarewaju** [comment]
@serniko97 are you testing the latest version from master?

**Comment by serniko97** [comment]
I'm having the same problem with the 2.6.4

**Comment by ifedapoolarewaju** [comment]
it's probably due to a race condition where you switch chat amid while oldermessages chat is loading for the previous chat. But yes, I'll be happy to review your PR :)
