### ISSUE TITLE
Instagram call checkpoint for this action!

### ISSUE THREAD

**Issue by ninabui2005** [ifedapoolarewaju/igdm#88]
when i try signing in, it keeps saying Instagram call checkpoint for this action! and then when i keep pressing it many times, it says Please wait a few minutes before you try again.

**Comment by udiudiudiudi** [comment]
if you are on wifi, with the computer and mobile on wifi, then no checkpoint

**Comment by alexmozzhakov** [comment]
Duplicate of #60
