### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by blanq2024** [ifedapoolarewaju/igdm#880]
Hi! I've been using idgm since last December.

I've recently changed my pc and been using it quite well before 2.6.3 update.
While update, the installation program exclaimed error describing that uninstall.exe doesn't exist.

So I deleted the program manually(deleted in the "appdata" folder etc. and searched and deleted the keys in the regedit.exe using keyword "igdm."

But since then, after I reinstalled the latest version of it, It just won't login.
It sends the verification mail, so I copy and paste it, but it won't be logged in,
verification pop-up comes up again, and resend the verification mail.

What do I have to do with this? I'm using the latest version of the Windows 10,
and trying to install the latest version of the igdm.

Thanks!

**Comment by ifedapoolarewaju** [comment]
What version are you testing with? 2.6.3? Or 2.6.4?

**Comment by blanq2024** [comment]
> What version are you testing with? 2.6.3? Or 2.6.4?
> […](#)
> On 8 Apr 2019, at 6:49 AM, duplicate-issues[bot] ***@***.***> wrote: Hey @blanq2024, We did a quick check and this issue looks very darn similar to #879 - the automatic updating just spins in the mud...it doesn't manage to work. #878 - dunno why just messages and someone's username automatically get removed today afternoon, please help to solve this issue, even i can't find the user name id again, it removed forever for me, #877 - Get stuck rendering old messages This could be a coincidence, but if any of these issues solves your problem then I did a good job 😄 If not, the maintainers will get to this issue shortly. Cheers, Your Friendly Neighborhood ProBot — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I tried on the both of them. .3 and .4.
'Cuz I was waiting for the update, expecting it could be fixed on the next version.
But none of them was working.
I think it worked fine when I was using .2, not so sure though.
