### ISSUE TITLE
Log on verification

### ISSUE THREAD

**Issue by crossracheal85** [ifedapoolarewaju/igdm#881]
I have now been sent 8 different verification codes none of which allow me to sign in

**Comment by TheBlinded** [comment]
I have a similar issue I think... double pass verification isn't supported... will be supported in a near future? Thanks a lot for your work!

**Comment by TheBlinded** [comment]
> I have a similar issue I think... double pass verification isn't supported... will be supported in a near future? Thanks a lot for your work!

But.. yes or not?? :-)

**Comment by ifedapoolarewaju** [comment]
hi, yes this is something that can be implemented in the future, however, I closed this ticket because it is a duplicate
