### ISSUE TITLE
error logging attribution

### ISSUE THREAD

**Issue by jaysilver** [ifedapoolarewaju/igdm#889]
A strange one here. When logging in, I am greeted with the message "Error logging attribution". I was able to install and use it without issues on another system earlier today. 

1. Tried reinstalling (with administrative rights)
2. Tried installing v2.1.0, gives me the following error: "Cookie sessionid you are searching found was either not found or not valid!"

Too bad, hope I can get some help with this <3

**Comment by RebeLKilleR** [comment]
I take same message. "error logging attribution".

1) Tried reinstalling (with administrative rights)
2) Reinstalling and opening with compatibility mode (Windows 7)

![image](https://user-images.githubusercontent.com/49659289/56163777-dead0880-5fd7-11e9-8b0b-1b53dd45e2e7.png)

I can't log in :'(

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
i have the same issue it just says error logging attribution please help or fix

**Comment by RebeLKilleR** [comment]
I didn't do anything but it's working properly right now.
I just changed the network and reboot. from a mobile network to a normal network. It's strange 💃

**Comment by jaysilver** [comment]
Turns out IG has a windows 10 app in the MS Store
