### ISSUE TITLE
limited DMs - only 20 messages

### ISSUE THREAD

**Issue by udiudiudiudi** [ifedapoolarewaju/igdm#89]
is this on propose that i see only 20 DMs and not the whole DMs i have in my normal instagram?

**Comment by keva13** [comment]
временное решение 

./instagram.js 41
> exports.getChat = function (session, chatId, offset) {
  return new Promise((resolve, reject) => {
	  Client.Thread.getById(session, chatId, offset).then(resolve).catch(reject)
  })

./main.js 66

> function getChat (evt, id, offset = 0, items = []) {
	instagram.getChat(session, id, offset).then((chat) => {
	items = items.concat(chat.items);
	if (chat.items.length < 19) {
		chat.items = items;
		mainWindow.webContents.send('chat', chat);
	} else {
		getChat(evt, id, items[items.length - 1].id, items)
	}
if (timeoutObj) clearTimeout(timeoutObj)
timeoutObj = setTimeout(getChat, pollingInterval, {}, id);
 }).catch(() => setTimeout(getChat, RATE_LIMIT_DELAY, evt, id))
 }

./node_modules/instagram-private-api/client/v1/constants.js 63

>    threadsShow: 'direct_v2/threads/<%= threadId %>/<%= maxId ? ("?max_id=" + maxId) : "" %>',

./node_modules/instagram-private-api/client/v1/thread.js 214

> Thread.getById = function (session, id, offset = 0) {
    if(_.isEmpty(id))
        throw new Error("`id` property is required!")
    return new Request(session)
        .setMethod('GET')
        .generateUUID()
        .setResource('threadsShow', {
            threadId: id,
			maxId: offset
        })
        .send()
        .then(function(json) {
            return new Thread(session, json.thread)
        })
};

**Comment by drigio** [comment]
@keva13 Your implementation requires changes in the instagram-api which is a dependency. So is it beneficial in these types of cases? Is there any other workaround for this?

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.5.1 please visit the site http://igdm.me to download the latest version
