### ISSUE TITLE
Messages dont refresh/load

### ISSUE THREAD

**Issue by oomartinoo** [ifedapoolarewaju/igdm#895]
All my chats are empty, Until I send a message. When I send a message it updates all the messages from both people in the chat. When I close or switch the chat, It wipes them till I send a message. 

I Never Receive messages, unless I send something.

We Need a Refresh/Reload Chat button.

**Comment by oomartinoo** [comment]
It seems to be working now, I was using the appimage. Which wasnt loading stuff correctly. Now ive loaded it via npm start and its working fine so far

**Comment by adamac2** [comment]
@oomartinoo I have the same issue, how did you load via npm because? I'm using ubuntu and am fairly new to it.
