### ISSUE TITLE
cannot log in ig dm

### ISSUE THREAD

**Issue by gxobeautyshop** [ifedapoolarewaju/igdm#897]
![image](https://user-images.githubusercontent.com/49932123/56630756-f1cd7180-6684-11e9-9087-48df6f368213.png)
![image](https://user-images.githubusercontent.com/49932123/56630766-fb56d980-6684-11e9-97c6-acf2b38afac4.png)

**Comment by aevlin** [comment]
same for mee too

**Comment by cjp4328** [comment]
same
