### ISSUE TITLE
Improve clarity in options status for example : send "seen" receipts

### ISSUE THREAD

**Issue by cnahuel** [ifedapoolarewaju/igdm#899]
the status of the options like, send "seen" receipts, it's not very clear
it could be shown like an checked list for example for better clarity and faster check

**Comment by onthez** [comment]
> the status of the options like, send "seen" receipts, it's not very clear
> it could be shown like an checked list for example for better clarity and faster check

I'm glad to see this suggestion already here. I came to make the same one.
The current menu item 'SEND "SEEN" RECEIPTS' presents confusion to the user.
Is that the status of what the current behavior is, or do I click that menu item if I want to send seen receipts.

As @cnahuel suggested it would be much better to have 'Send "seen" receipts' accompanied by a checkbox next to it to indicate if that is enabled or disabled.
Or, if you don't want to mess with adding a checkbox, consider change the text to read:
'Disable send "seen" receipts' and 'Enable send "seen" receipts'
or
'Send "seen" receipts - currently disabled' and 'Send "seen" receipts - currently enabled'
or similar.
