### ISSUE TITLE
no configs given

### ISSUE THREAD

**Issue by bloop-myton** [ifedapoolarewaju/igdm#900]
when i tried logging in it would say no configs given and wont let me log in even though i got the password and username right.

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
same here

**Comment by angelg145** [comment]
SAME

**Comment by MC117243** [comment]
SAME.

**Comment by instagramsofii** [comment]
same

**Comment by karen1234567** [comment]
**SAME.**

**Comment by Justice04** [comment]
Yup, same. You'd think after 5 hours and multiple reports, they'd get a hint and do something about it.

**Comment by tahaa48** [comment]
samee

**Comment by tahaa48** [comment]
fuck sake

**Comment by omaraldahi** [comment]
same

**Comment by ismailemin** [comment]
same

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed. Please restart your IGdm app so it can update to the latest version
