### ISSUE TITLE
jazminsarahiarias612@gmail.com

### ISSUE THREAD

**Issue by sarahiarias14** [ifedapoolarewaju/igdm#905]
no puedo entrar en igdm

**Comment by Kyloren333** [comment]
Yo tampoco, y no se que pasa, y parece ser que es un problema de la app, no de la cuenta, porque tengo dos cuentas, y no me deja entrar con ninguna de las dos, y no tengo movil, me lo quitaron, me rollo, y estoy teniendo una conversacion muy importante en las dos cuentas

**Comment by sarahiarias14** [comment]
si que raro xq si puedo entrar en mi cuanta pero no puedo chatiar
