### ISSUE TITLE
wont let me log in

### ISSUE THREAD

**Issue by b8ked** [ifedapoolarewaju/igdm#908]
everytime i try to log in it says "no configs given" and wont let me in. i know im putting everything in correctly. some help would be appreciated.

**Comment by Kyloren333** [comment]
Yes, to me too, and I didn't understand the help, please, it says no configs give, and I can't do anything, I don't receive an email about or anything, what do I do? I have people to speak to

**Comment by Kyloren333** [comment]
I have two accounts, and in both of them it say the smae, so it's not a problem of the account, It was working properly yesterday, I just logged out to enter my other account, and this happened, now I can't log in to non of them
