### ISSUE TITLE
No configs given

### ISSUE THREAD

**Issue by stevenkwlee** [ifedapoolarewaju/igdm#912]
Hey, I'm getting an error upon trying to log in and using the platform ... 

I got my username & password right, and 2-step authentication is disabled, but still, I get the error :

"No configs given" 

It seems like others are also having the same problem.

![no configs](https://user-images.githubusercontent.com/50036253/56843257-539c0000-686c-11e9-9eae-c3c95c854293.jpg)

Please fix, thanks!

**Comment by adrian77256** [comment]
Yes we are al having this problem.

**Comment by cotsia** [comment]
i have this problem too can anyone help me to solve it it is an emergency
