### ISSUE TITLE
No configs gives IG:dm

### ISSUE THREAD

**Issue by liligarciatb** [ifedapoolarewaju/igdm#915]
I tried loging in, but says no configs given
I got the username and password right!!
Need help!

**Comment by kellygibsn** [comment]
I tried loging in, but says no configs given
I got the username and password right
![images](https://user-images.githubusercontent.com/50039538/56845209-1416f780-68f0-11e9-83df-749056e885c3.jpg)

**Comment by gabiramirezv29** [comment]
I tried logging in, but says no configs given
I got the username and password right
Help me

**Comment by gabiramirezv29** [comment]
Who can help me please, I have correct username and password and says No Configs Given... how can I fix it?

**Comment by gabiramirezv29** [comment]
> 
> 
> I tried loging in, but says no configs given
> I got the username and password right!!
> Need help!
I have the same problem and I do not know what to do...
