### ISSUE TITLE
No Configs Given

### ISSUE THREAD

**Issue by XXQUEENXX** [ifedapoolarewaju/igdm#916]
I've been trying to log on all day but all it says is no configs given, Please help!!

**Comment by tahaa48** [comment]
please fix

**Comment by tharu5ha** [comment]
OMGG WHAT IS HAPPENING

**Comment by tharu5ha** [comment]
> I've been trying to log on all day but all it says is no configs given, Please help!!

i need to text my girlfriend FFS!!!!
