### ISSUE TITLE
error no configs given

### ISSUE THREAD

**Issue by tahaa48** [ifedapoolarewaju/igdm#918]
i try to log in and error says no configs given please fix this asap its urgent 
<img width="1440" alt="Screenshot 2019-04-27 at 8 48 18 am" src="https://user-images.githubusercontent.com/50040206/56845391-39dcd600-68c9-11e9-8ee8-9302333939b8.png">

**Comment by tahaa48** [comment]
i need the answer on how to fix pls

**Comment by ArmaanSodhi** [comment]
i am having the same problem, pls tell me what to do

**Comment by mnagy883** [comment]
how we can fiz it please tell us
