### ISSUE TITLE
igdm configs not given

### ISSUE THREAD

**Issue by ArmaanSodhi** [ifedapoolarewaju/igdm#921]
not able to login due to configs not given, pls look into it asap

**Comment by FlaMax404** [comment]
same problem here, it updated for me and now I cannot login

**Comment by Khadijah997** [comment]
> same problem here, it updated for me and now I cannot login

same it says no configs, you know what to do?

**Comment by harshinibanoth** [comment]
same it says no config given

**Comment by harshinibanoth** [comment]
plz some one solve my problem

**Comment by maya9128** [comment]
Hello I've been using igdm for some time but today on 27/4/2019 there is a problem come to me message no configs given
