### ISSUE TITLE
why my igdm pro says no configs given

### ISSUE THREAD

**Issue by harshinibanoth** [ifedapoolarewaju/igdm#924]

**Comment by harshinibanoth** [comment]
plz solve my problem as soon as possible and quick

**Comment by harshinibanoth** [comment]
whats wrong with this why dont this solve the problem

**Comment by harshinibanoth** [comment]
plz  some one help me it is important for me too speak with my love

**Comment by Immy0208** [comment]
Please help me log in to my account. I really need to talk to my friends through my DM's but it won't let me.

**Comment by Robertorc83** [comment]
please help with his issue i need it for my work
