### ISSUE TITLE
i can't log in 

### ISSUE THREAD

**Issue by tanusree101** [ifedapoolarewaju/igdm#925]
when I try to log in it say No configs given
This app is not affiliated with Instagram. You can visit the open source project here.

We never store your password.

**Comment by tahaa48** [comment]
everyone has this and the are not  doing anything

**Comment by harshinibanoth** [comment]
i even have same problem can u help me out plzzzz

**Comment by OmkarBhosdiwala** [comment]
We cannot do anything cuz the power to change any of the settings lies in their hands
