### ISSUE TITLE
No Configs Given

### ISSUE THREAD

**Issue by Lijjy** [ifedapoolarewaju/igdm#931]
It's annoying when you try to log in and it won't let you.  I got this app so I could speak to my friends, but now it seems pointless if it won't work

**Comment by Lijjy** [comment]
what issues?

**Comment by alreemhashmii** [comment]
my igdm is not working, it says no configs given

**Comment by aadi0110** [comment]
same

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
same

**Comment by aadi0110** [comment]
how can fix it ??????

**Comment by mnagy883** [comment]
me too

**Comment by mylefttoe** [comment]
same :(

**Comment by hepcathelm** [comment]
anyone know how can i fix it??

**Comment by miniatvre** [comment]
same.. and today is a day that I reallyyy need to be able to check my messages so I hope it gets fixed soon

**Comment by marcosesoj** [comment]
Já está assim há mais de 24 horas.

**Comment by Robertorc83** [comment]
anyone know how can i fix it?

**Comment by bluekitsune** [comment]
I don't understand this website at all, but once mine was able to update itself, it stopped working with the No Configs message.

**Comment by depiestheticscaballito** [comment]
same!
