### ISSUE TITLE
It says " No configs given" 

### ISSUE THREAD

**Issue by tharu5ha** [ifedapoolarewaju/igdm#932]
Everyone has the same problem BUT WHYYYYY???

**Comment by Immy0208** [comment]
I have the same problem to. It won't let me log in to see my DM. Can anyone please tell my how I can log in to my account?

**Comment by alreemhashmii** [comment]
Same

**Comment by aadi0110** [comment]
same

**Comment by karen1234567** [comment]
Same.

**Comment by HSoeren** [comment]
Same, used it, then it autoupdated afterwards broken - "no configs given" Error
