### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by TabyKhan** [ifedapoolarewaju/igdm#939]
Did anyone find solution for opening IGDM. It is still showing "no configs"

**Comment by alreemhashmii** [comment]
nope

**Comment by macchisara99** [comment]
yo tampoco puedo entrar

**Comment by elenacorral** [comment]
Me pasa lo mismo, es horrible xq estoy castigada sin móvil y no puedo hablar con mis amigos

**Comment by macchisara99** [comment]
que se puede hacer para poder entrar?
