### ISSUE TITLE
Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443

### ISSUE THREAD

**Issue by minnu1234567** [ifedapoolarewaju/igdm#94]
Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443

**Comment by othreecodes** [comment]
+1 same issue here

**Comment by ifedapoolarewaju** [comment]
@minnu1234567 @othreecodes do you mind sharing what type of machine you tested this?

**Comment by LucsaKun** [comment]
**Error: getaddrinfo ENOTFOUND i.instagram.com i.instagram.com:443** same issue.

Any news?

**Comment by nabyle** [comment]
Il existe 2 solutions connues pour résoudre ce problème:
Exécutez-le en tant qu'administrateur en mode de compatibilité Windows 7. Pour faire ça:
Faites un clic droit sur le fichier d'installation (c'est-à-dire le programme d'installation IG: dm)
Allez dans "Propriétés"
Allez dans l'onglet "Compatibilité"
Cliquez sur "Exécuter ce programme en mode de compatibilité pour:"
Sélectionnez "Windows 7"
En bas, cochez la case "Exécuter ce programme en tant qu'administrateur"
Cliquez sur le bouton "Appliquer" pour appliquer les modifications.
Ensuite, essayez de réexécuter le programme d'installation.
