### ISSUE TITLE
No configs given

### ISSUE THREAD

**Issue by binteadam765** [ifedapoolarewaju/igdm#942]
I have been able to use IG:DM software but now for some reason a sign in red comes up saying "error no configs given" could this please be fixed...Plz fast

**Comment by binteadam765** [comment]
Plz solve this issue as soon as possible

**Comment by marcosesoj** [comment]
Essa porcaria já está fora do ar há mais de 24 horas. Horrível.

**Comment by binteadam765** [comment]
what the hell!

**Comment by tharu5ha** [comment]
OMGG PLEASE SOLVE THISSSS !!! I NEED TO TEXT MY PREGNANT GF!!!

**Comment by tharu5ha** [comment]
OMGG PLEASE SOLVE THISSSS !!! I NEED TO TEXT MY PREGNANT GF!!!

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
oof ur pregnant girlfriend lool

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
wheres ur phone

**Comment by binteadam765** [comment]
yes! i am thinking the same thing...where is ur phone??

**Comment by tharu5ha** [comment]
just found it LOL

**Comment by tharu5ha** [comment]
why wont these guys solve the issue though?

**Comment by binteadam765** [comment]
i don't know ...

**Comment by tharu5ha** [comment]
OMG im cryinggggggg

**Comment by tharu5ha** [comment]
OMG im cryinggggggg

**Comment by tharu5ha** [comment]
anyone wanna follow me on INSTAGRAM its @t_h_a_r_u_5_h_a

**Comment by tharu5ha** [comment]
anyone wanna follow me on INSTAGRAM its @t_h_a_r_u_5_h_a

**Comment by binteadam765** [comment]
> anyone wanna follow me on INSTAGRAM its @t_h_a_r_u_5_h_a

Seriously???

**Comment by tharu5ha** [comment]
yh

**Comment by tharu5ha** [comment]
yh

**Comment by binteadam765** [comment]
we are worried about Dm...nd you are talking about following

**Comment by tharu5ha** [comment]
why u worried?

**Comment by tharu5ha** [comment]
why u worried?

**Comment by binteadam765** [comment]
because i need it

**Comment by tharu5ha** [comment]
why so much?

**Comment by tharu5ha** [comment]
bruv why isnt this issue being fixed by now?!??!!!!!!!!!! IM RAGING if it isnt fixed by tommorow

**Comment by darwish0** [comment]
> Hey @binteadam765,
> 
> We did a quick check and this issue looks very darn similar to
> 
> * [#941 - no puedo abrir mi cuenta](941)
> * [#940 - idgm no config](940)
> * [#939 - Solution](939)
> 
> This could be a coincidence, but if any of these issues solves your problem then I did a good job 
> 
> If not, the maintainers will get to this issue shortly.
> 
> Cheers,
> Your Friendly Neighborhood ProBot

help guys i cant log in to my account its saying no configs given

**Comment by tharu5ha** [comment]
@darwish0 Same fammmm everyone has the same problem with IGDM

**Comment by darwish0** [comment]
guys help i cant log in to my account its saying no configs given
@dublicate-issuse

**Comment by binteadam765** [comment]
> help guys i cant log in to my account its saying no configs given

yes darwish we have no option ..just wait

**Comment by binteadam765** [comment]
some people found a code but they dont know how to use it

**Comment by darwish0** [comment]
wich code ?

**Comment by tharu5ha** [comment]
@binteadam765 what do you mean by "people found a code"??

**Comment by MC117243** [comment]
@tharu5ha 
@darwish0 
If you go to the code portion of the github, there is a code to fix it, But we can't figure out how to execute it.

**Comment by binteadam765** [comment]
@MC117243 yes you are right!Thanks for explaination

**Comment by tharu5ha** [comment]
@MC117243  @binteadam765  lemme figure this out then

**Comment by tharu5ha** [comment]
@MC117243  @binteadam765  lemme figure this out then

**Comment by binteadam765** [comment]
@MC117243 okk

**Comment by tharu5ha** [comment]
@ifedapoolarewaju how do we use your damn code?

**Comment by tharu5ha** [comment]
@ifedapoolarewaju how do we use your damn code?

**Comment by MC117243** [comment]
@tharu5ha 
That's not going to help with anything.
Write a nice email to him, You can find his personal email on his profile, stating that you need this to work and that most of us aren't smart, so can he just put update 2.6.5 on the website pre-ready to run, requiriing us to do no work.

**Comment by tharu5ha** [comment]
@tharu5ha YEAH!! thx

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
its so annoying

**Comment by tharu5ha** [comment]
@iwantigdmtoworkpleaseiluvit i know son.. just emailed the CODE FIXER and should get a reply soon...I HOPE

**Comment by binteadam765** [comment]
who is code fixer???

**Comment by tharu5ha** [comment]
@binteadam765 the one who created the code for fixing this issue

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
fucking pisstake

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
@tharu5ha  anything?

**Comment by tharu5ha** [comment]
@iwantigdmtoworkpleaseiluvit nope

**Comment by tharu5ha** [comment]
@iwantigdmtoworkpleaseiluvit oh wait I got "I am currently trying to do a release for the changes I made to fix the issue. I’ll close the open issues after It is released." from him

**Comment by MC117243** [comment]
@tharu5ha 
It's fixed, download the better version off website.

**Comment by tharu5ha** [comment]
@MC117243 yes i know

**Comment by tharu5ha** [comment]
@MC117243 yes i know
