### ISSUE TITLE
how to apply released code to the actual program

### ISSUE THREAD

**Issue by MC117243** [ifedapoolarewaju/igdm#945]
So I'm having the the config problem and I saw that a code that would fix it is released. How would i apply that new code to the program? I'm new to github and programming, So could someone please help.

**Comment by binteadam765** [comment]
which code???

**Comment by tahaa48** [comment]
look in source code iits. a json file w the "fix no configs" but no one knows how to use it

**Comment by binteadam765** [comment]
where

**Comment by binteadam765** [comment]
can u send me screenshot

**Comment by tahaa48** [comment]
![Screen Shot 2019-04-27 at 10 09 33 PM](https://user-images.githubusercontent.com/50040206/56854050-28cbad80-6939-11e9-8eec-daa854ee87c8.png)

**Comment by tahaa48** [comment]
idk how to use it tho

**Comment by binteadam765** [comment]
i cant find out

**Comment by redwrdz** [comment]
bro how do you fix it with the code bruh i'm to stupid for that high tech bullshit

**Comment by MC117243** [comment]
@tahaa48 
When downloaded to windows PC, it seems like a picture file for publisher. 
When clicked on so it runs, It does nothing.
I think the dude who invented this needs to just publish a new update with this in it, because most of us are too dumb to do whatever he wants us to do.

**Comment by MC117243** [comment]
@ifedapoolarewaju 
How can we implement your code?
Alot of us would like to use your program, some need it while others want it. We understand you may be busy to, Could you please just make 2.6.5 into an offical version and put it on the website, because most users do not know how to use the code you released, Most of us aren't that techy, So Could you please help us out here?

**Comment by TobiHoKage** [comment]
either install using npm, or download the new image from their website. 
both methods work fine on linux.

**Comment by MC117243** [comment]
@TobiHoKage 
How long does the Downloading application update take?

**Comment by TobiHoKage** [comment]
@MC117243 less than few minutes depending on your internet. use npm, it is about 53MBs.

**Comment by MC117243** [comment]
okay.
