### ISSUE TITLE
IG:dm No config error.

### ISSUE THREAD

**Issue by yagiZraekeN** [ifedapoolarewaju/igdm#947]
Please resolve "No configs given" error. I wanna message to my friends

**Comment by MC117243** [comment]
There is a solution, Just most of us are dumb to figure out how to apply it. He released a code that should solve it except we can't apply it.

**Comment by patricia2006** [comment]
what is the solution

**Comment by yagiZraekeN** [comment]
> 
> 
> There is a solution, Just most of us are dumb to figure out how to apply it. He released a code that should solve it except we can't apply it.

Please help me :(
