### ISSUE TITLE
blank column in the middle

### ISSUE THREAD

**Issue by hoanglam1233** [ifedapoolarewaju/igdm#95]
I dont understand why did this happen on my 1st time use this app but I think i should feedback you about this
![untitled](https://user-images.githubusercontent.com/36809243/36638908-e645a520-1a32-11e8-923f-bc0d1e79f5d3.png)
and 1 more thing, I try to open the setup file of the previous version and nothing happened.

**Comment by ifedapoolarewaju** [comment]
@hoanglam1233 Hi this is the pre-release for version 2.4.0 that was badly packaged. Please install version 2.3.1 instead. Which is here https://github.com/ifedapoolarewaju/igdm/releases/tag/v2.3.1

**Comment by ifedapoolarewaju** [comment]
a properly built version has now been released https://github.com/ifedapoolarewaju/igdm/releases/download/v2.4.0/IGdm-2.4.0.exe
