### ISSUE TITLE
no configs given

### ISSUE THREAD

**Issue by zoejaffari** [ifedapoolarewaju/igdm#951]
can someone please help me out?? PLEASE UPLOAD THE IGDM!!!

**Comment by zoejaffari** [comment]
Stop saying that you stupid bot ugh!

**Comment by zoejaffari** [comment]
Everyone has this issue and no one is trying to fix this shit!

**Comment by zoejaffari** [comment]
No one is fixing this issue so please I'm begging you i need it please
________________________________

**Comment by TobiHoKage** [comment]
either install using npm, or download the new image from their website. 
both methods work fine on linux.

**Comment by darwish0** [comment]
code its 949  but then what i will do ?
