### ISSUE TITLE
IG:DM is broken

### ISSUE THREAD

**Issue by marcosesoj** [ifedapoolarewaju/igdm#953]
The problem persists for more than 24 hours, and nobody, exactly anyone, came to give us a clarification due to the cause. We're just here overloading the tickets with the same pending, having a bot answering us with the same automatic response. **This is broken**!

**Comment by redwrdz** [comment]
Mine works now

**Comment by marcosesoj** [comment]
![image](https://user-images.githubusercontent.com/49665319/56855892-26138d00-6926-11e9-87e9-da3ada7366b7.png)

**Comment by redwrdz** [comment]
My dm just updated when i tried launching it up again and it workd now

**Comment by marcosesoj** [comment]
Really. Now it's working. Thank you.

**Comment by redwrdz** [comment]
Ofc

**Comment by iwantigdmtoworkpleaseiluvit** [comment]
yh its working now

**Comment by alreemhashmii** [comment]
it doesnt for me
