### ISSUE TITLE
IG DM "No configs given" error solution!

### ISSUE THREAD

**Issue by yagiZraekeN** [ifedapoolarewaju/igdm#956]
Hei boiz i found this issue solution. If you download IGdm 2.5 then it will open! 
Uninstall 2.6.4 igdm after download 2.5
i gave you link : https://igdm.software.informer.com/2.5/

**Comment by ifedapoolarewaju** [comment]
> Hei boiz i found this issue solution. If you download IGdm 2.5 then it will open!

you don't need to do this. You just need to restart your IGdm app and it will update to the latest version containing a fix for this issue
