### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by rohangupta3** [ifedapoolarewaju/igdm#97]
The app opens but then it goes to the normal menu but no names appear, I have to uninstall then reinstall whcih takes a long time

Thank you

**Comment by ifedapoolarewaju** [comment]
@rohangupta3 on what platform are you running this? Plus can you please share screenshots, so we get a better picture?

**Comment by Megz00269900** [comment]
Sometimes not all the messages will appear in a chat. So when I try to type something to this one person it wont send when I press enter it will just go to another line or paragraph. When that person sends me something I get the notification although it wont pop up in the chat itself just the name. Any suggestions?

**Comment by rohangupta3** [comment]
This happens to me all the time. I also get a Java popup which never used to happen.
Rohan
 

    On Thursday, 4 April 2019, 03:36:19 BST, Megz00269900 <notifications@github.com> wrote:  
 
 
Sometimes not all the messages will appear in a chat. So when I try to type something to this one person it wont send when I press enter it will just go to another line or paragraph. When that person sends me something I get the notification although it wont pop up in the chat itself just the name. Any suggestions?
