### ISSUE TITLE
I changed my password and immediately tried to login, failed all of the tries

### ISSUE THREAD

**Issue by adolfovalle** [ifedapoolarewaju/igdm#970]
It's not detecting changes on password from ~1 minute, i can't login right after changing my password

**Comment by ifedapoolarewaju** [comment]
Are you able to login now?

Ifedapo Olarewaju  | Software Engineer
Mobile: +2347083455063 | ifedapoolarewaju@gmail.com

**Comment by adolfovalle** [comment]
not able to login as of today

**Comment by ifedapoolarewaju** [comment]
Are you able to login on the mobile app though?
