### ISSUE TITLE
Couldn't upload image

### ISSUE THREAD

**Issue by raphaelbelly** [ifedapoolarewaju/igdm#978]
Hello.

I can't send pictures in direct messages.
It says "Your file is being uploaded" then "Image upload failed. :( Please ensure your image is in .jpg format"

My file is JPG (from Lightroom).

![01](https://user-images.githubusercontent.com/50667855/57781605-d527d500-772a-11e9-8e75-b8e3887708d7.JPG)
![02](https://user-images.githubusercontent.com/50667855/57781609-d78a2f00-772a-11e9-8a8b-88b627bb8089.JPG)

**Comment by edraven** [comment]
Same issue here with lightroom jpg's
