### ISSUE TITLE
the credentials and the password 

### ISSUE THREAD

**Issue by whoisdenis** [ifedapoolarewaju/igdm#984]
Veran, abajo de vuestra aplicación, IG:dm, dice literalmente, we never store your credentials or your password, pero hoy me encuentro que alguien de vuestra oficina, inicio sesión en mi cuenta de instagram, desde un teléfono móvil: zte blade a5. EXIJO JUSTIFICACIONES DE ESTE HECHO U OS DEMANDARÉ. Gracias. 
Atte: Denis Dumitru Mocut ; con el nombre de usuario de instagram de @_whoisdenis 
Correo de contacto: jm9741204@gmail.com

**Comment by ifedapoolarewaju** [comment]
your account was not logged into by anyone. Please see my comment here https://github.com/ifedapoolarewaju/igdm/issues/1008#issuecomment-504681410
