### ISSUE TITLE
Signing back in 

### ISSUE THREAD

**Issue by SHIELD22** [ifedapoolarewaju/igdm#991]
I tried to log back in under my user name  but it's not letting back in with my new password 
where do i find the reg log for instragram so I can sigh out then sign back in with my new password .

**Comment by SHIELD22** [comment]
So Not sure what Going on now in  the main IGDM where show my account on the right hand side at the top i'm in that page it let's me in there but not the IGDM i had in my taskbar

**Comment by alemeddin1234** [comment]
benimkide aynı sorun
